import {z} from 'zod';
import {shippingZoneSchema,shipsTo,assertShippingProducts} from '../../../shared/shipping.ts';
import {readLimitedBody} from '../../../shared/request-body.ts';
import {hashValue,matchesMagic} from '../../../shared/security.ts';
import {customerCatalog} from '../../../shared/public-data.ts';
import {checkoutSchema} from '../../../shared/validation.ts';
import {cartPrice,contactHash,publicationErrors,mediaAllowed,uniqueCartLines,validateDiscount,parity} from '../../../shared/logic.ts';
import {productSchema} from '../../../shared/product-schema.ts';
import {settingsSchema} from '../../../shared/settings-schema.ts';
import {reviewPhotoAllowed} from '../../../shared/review-media.ts';
import type {AdminData,Catalog,Product,Discount,Media,MediaCleanupJob} from '../../../shared/domain.ts';
import {db,rpc,env,settings,readiness,identity,requireRole,requireCustomer,rate,antiAbuse,respond,safeError,snake} from '../_shared/server.ts';
const id=z.string().min(1).max(100);const text=z.string().trim().max(2000);const l10n=z.object({ar:text,he:text,en:text}).strict();
const mediaSchema=z.object({id,src:z.string().max(2048),storagePath:z.string().max(512).optional(),alt:l10n,kind:z.enum(['image','video','certificate']),width:z.number().int().positive().max(20000),height:z.number().int().positive().max(20000),position:z.number().int().nonnegative(),mime:z.string().max(100),bytes:z.number().int().positive().optional()}).strict();
const taxonomy=z.object({id,slug:id.regex(/^[a-z0-9-]+$/),name:l10n,description:l10n,image:z.string().max(2048),position:z.number().int(),active:z.boolean()}).strict();
const entitySchemas:Record<string,z.ZodTypeAny>={categories:taxonomy,collections:taxonomy,media:mediaSchema,zones:shippingZoneSchema,pages:z.object({id,slug:id.regex(/^[a-z0-9-]+$/),kind:z.enum(['faq','education','policy']),title:l10n,body:l10n,status:z.enum(['draft','published']),legalReviewed:z.boolean()}).strict(),sections:z.object({id,kind:z.enum(['hero','collections','categories','standard','editorial','education','journey','story','packaging']),enabled:z.boolean(),position:z.number().int(),title:l10n,body:l10n,cta:l10n,href:z.string().max(200).regex(/^\/(?!\/)/),image:z.string().max(2048),selection:z.array(id).max(100),layout:z.enum(['split','full','grid'])}).strict(),reviews:z.object({id,status:z.enum(['pending','approved','rejected','hidden'])}),inquiries:z.object({id,status:z.enum(['open','contacted','quoted','converted','closed'])}),discounts:z.object({id,code:z.string().trim().min(1).max(50),kind:z.enum(['fixed','percentage']),value:z.number().int().positive(),active:z.boolean(),startsAt:z.string().datetime().nullable(),endsAt:z.string().datetime().nullable(),usageLimit:z.number().int().positive().nullable(),used:z.number().int().nonnegative(),minimumSubtotal:z.number().int().nonnegative(),productIds:z.array(id),collectionIds:z.array(id)}).strict()};
async function mediaCheck(m:{src:string;storagePath?:string}){if(m.storagePath){if(!await rpc<boolean>('thuraya_media_confirmed',{p_path:m.storagePath}))throw new Error('invalid_media')}else if(!/^\/media\/[a-zA-Z0-9._-]+$/.test(m.src))throw new Error('invalid_media')}
async function decorate<T extends Catalog>(d:T):Promise<T>{
d.settings=readiness(d.settings);const base=env('SUPABASE_URL')+'/functions/v1/media-delivery';const admin='media' in d;
if(admin){const retry=await rpc<{id:string;uncertain:boolean;firstAttemptAt:string|null}[]>('thuraya_notification_retry_state');const receipts=await rpc<{id:string;receiptState:string;receiptAt:string;receiptAlert:string|null}[]>('thuraya_receipt_projection');const attestations=await rpc<{id:string;acceptanceEvidence:'operator_attestation';acceptanceAt:string}[]>('thuraya_reconciliation_projection');for(const n of (d as unknown as AdminData).notifications)Object.assign(n,retry.find(r=>r.id===n.id),receipts.find(r=>r.id===n.id),attestations.find(r=>r.id===n.id))}
for(const p of d.products)for(const m of p.media)if(m.storagePath){
if(admin){const {data}=await db.storage.from('product-media').createSignedUrl(m.storagePath,300);if(data)m.src=data.signedUrl}else m.src=base+'?id='+encodeURIComponent(m.id)
}
if(admin){
for(const m of (d as unknown as AdminData).media)if(m.storagePath){const {data}=await db.storage.from('product-media').createSignedUrl(m.storagePath,300);if(data)m.src=data.signedUrl}
for(const r of d.reviews){const signed=await Promise.all(r.media.map(async path=>{const {data}=await db.storage.from('review-media').createSignedUrl(path,300,{transform:{width:640,resize:'contain',quality:90}});return data?.signedUrl||''}));r.media=signed.filter(Boolean)}
}else{
for(const r of d.reviews)r.media=r.status==='approved'?r.media.map(path=>base+'?review='+encodeURIComponent(path)):[];
}
const references=await rpc<{entity:string;recordId:string;media:Media}[]>('thuraya_cms_media');
for(const [entity,rows] of [['content_sections',d.sections],['categories',d.categories],['collections',d.collections]] as const)for(const row of rows){
const ref=references.find(r=>r.entity===entity&&r.recordId===row.id);if(!ref)continue;
const media=ref.media;
if(admin){const preview=(d as unknown as AdminData).media.find(m=>m.id===media.id);if(preview)row.image=preview.src}
else{row.image=media.storagePath?base+'?id='+encodeURIComponent(media.id):media.src;row.imageMedia={id:media.id,src:row.image,alt:media.alt,kind:media.kind,width:media.width,height:media.height,mime:media.mime,position:media.position}}
}
return d;
}
Deno.serve(async req=>{if(req.method==='OPTIONS')return respond(req,{});if(req.method!=='POST')return respond(req,{error:'method_not_allowed'},405);try{const raw=new TextDecoder('utf-8',{fatal:true}).decode(await readLimitedBody(req,500000));const {action,payload:p}=z.object({action:z.string().max(50),payload:z.record(z.unknown()).default({})}).parse(JSON.parse(raw));await rate(req,action,action==='catalog'?120:20);let result:unknown=null;
switch(action){
case 'catalog':{const d=await decorate(await rpc<Catalog>('thuraya_snapshot'));result=customerCatalog(d);break}
case 'admin-data':{const u=await requireRole(req,'dashboard');const d=await decorate(await rpc<AdminData>('thuraya_snapshot',{p_admin:true}));if(u.role==='content_manager'){d.orders=[];d.customers=[];d.inquiries=[];d.discounts=[];d.notifications=[];d.privateProducts=[];d.audit=[]}if(u.role==='order_manager'){d.privateProducts=[];d.discounts=[];d.audit=[];d.media=[];d.orders=d.orders.map(order=>({...order,internalNotes:'',supplierReference:''}))}result=d;break}
case 'place-order':{const input=checkoutSchema.parse(p);uniqueCartLines(input.lines);await antiAbuse(input.turnstileToken);const s=readiness(await settings());if(!s.paymentMethods.some(m=>m.id===input.paymentMethod&&m.enabled&&m.ready))throw new Error('payment_unavailable');const u=await identity(req);const stable={...input,turnstileToken:undefined,customerId:u?.id??null};result=await rpc('thuraya_place_order',{p_input:input,p_email_hash:await contactHash(input.email,env('TRACKING_HASH_SECRET')),p_phone_hash:await contactHash(input.phone,env('TRACKING_HASH_SECRET')),p_request_hash:await hashValue(JSON.stringify(stable),env('TRACKING_HASH_SECRET')),p_customer:u?.id??null});break}
case 'quote':{const q=z.object({lines:checkoutSchema.shape.lines,zoneId:id,city:checkoutSchema.shape.city,country:z.literal('IL'),code:z.string().max(50)}).parse(p);const d=await rpc<AdminData>('thuraya_snapshot',{p_admin:true});const zone=d.zones.find(x=>x.id===q.zoneId&&shipsTo(x,q.country,q.city));if(!zone)throw new Error('shipping_unavailable');assertShippingProducts(q.lines,d.products,q.country);const dis=q.code?d.discounts.find(x=>x.code.toUpperCase()===q.code.toUpperCase()):undefined;if(q.code&&!dis)throw new Error('discount_unavailable');const sub=cartPrice(q.lines,d.products,0).subtotal;result=cartPrice(q.lines,d.products,d.settings.freeShippingThreshold!==null&&sub>=d.settings.freeShippingThreshold?0:zone.price,dis);break}
case 'track-order':{const q=z.object({number:z.string().max(50),contact:z.string().max(254)}).parse(p);result=await rpc('thuraya_track',{p_number:q.number.trim().toUpperCase(),p_contact_hash:await contactHash(q.contact,env('TRACKING_HASH_SECRET'))});break}
case 'customer-orders':result=await rpc('thuraya_customer_orders',{p_customer:(await requireCustomer(req)).id});break;
case 'change-order':{const u=await requireRole(req,'orders');const q=z.object({id,status:z.enum(['order_received','payment_pending','payment_confirmed','in_production','quality_check','ready_to_ship','shipped','delivered','cancelled','refunded'])}).parse(p);result=await rpc('thuraya_change_order',{p_id:q.id,p_status:q.status,p_actor:u.id});break}
case 'update-order':{const u=await requireRole(req,'orders');const q=z.object({id,patch:z.object({internalNotes:text.optional(),supplierReference:text.optional(),safeTrackingUrl:z.string().url().startsWith('https://').nullable(),etaMin:z.number().int().nonnegative(),etaMax:z.number().int().nonnegative()}).strict()}).parse(p);if(q.patch.etaMax<q.patch.etaMin)throw new Error('invalid_delivery');if(!['owner','admin'].includes(u.role)&&('internalNotes'in q.patch||'supplierReference'in q.patch))throw new Error('forbidden');result=await rpc('thuraya_private_write',{p_action:'order',p_value:{id:q.id,...q.patch},p_actor:u.id});break}
case 'save-entity':{const entity=z.string().parse(p.entity);const area:Record<string,string>={products:'products',categories:'categories',collections:'collections',sections:'content',pages:'content',zones:'shipping',reviews:'reviews',inquiries:'inquiries',discounts:'promotions',media:'media'};if(!area[entity])throw new Error('forbidden');const u=await requireRole(req,area[entity]);if(entity==='products'){const v=productSchema.parse(p.value) as Product; // Strict domain validation additionally backed by relational constraints.
if(!v||v.isDemo||!Array.isArray(v.variants)||v.variants.length>200||!Array.isArray(v.axes)||v.axes.length>8)throw new Error('invalid_product');id.parse(v.id);id.regex(/^[a-z0-9-]+$/).parse(v.slug);for(const k of ['name','shortDescription','description','seoTitle','seoDescription','included','care'] as const)l10n.parse(v[k]);for(const m of v.media){mediaSchema.parse(m);await mediaCheck(m)}if(v.status==='published'&&publicationErrors(v,p.override===true&&u.role==='owner').length)throw new Error('publication_incomplete');result=await rpc('thuraya_save_product',{p:v,p_actor:u.id,p_override:p.override===true});}else{const v=entitySchemas[entity].parse(p.value);if(entity==='discounts')validateDiscount(v as Discount);if(entity==='media')await mediaCheck(v);if(entity==='sections'&&v.enabled&&(!parity(v.title)||!parity(v.body)||!parity(v.cta)))throw new Error('publication_incomplete');if((entity==='categories'||entity==='collections')&&v.active&&!parity(v.name))throw new Error('publication_incomplete');if(entity==='pages'&&v.status==='published'&&(!['ar','he','en'].every(l=>v.title[l].trim()&&v.body[l].trim())||v.kind==='policy'&&!v.legalReviewed))throw new Error('publication_incomplete');result=await rpc('thuraya_admin_write',{p_entity:entity,p_value:snake(v),p_actor:u.id})}break}
case 'reorder-sections':{const u=await requireRole(req,'content');const ids=z.array(z.string().min(1).max(100)).max(100).parse(p.ids);result=await rpc('thuraya_reorder_sections',{p_ids:ids,p_actor:u.id});break}
case 'reorder-taxonomy':{const u=await requireRole(req,'content');const input=z.object({entity:z.enum(['categories','collections']),ids:z.array(z.string().min(1).max(100)).min(1).max(100)}).strict().parse(p);result=await rpc('thuraya_reorder_taxonomy',{p_entity:input.entity,p_ids:input.ids,p_actor:u.id});break}
case 'save-settings':{const u=await requireRole(req,'settings');const current=await settings();const s=settingsSchema.parse({...current,...p.settings as object});if(s.currency!=='ILS'||!Number.isInteger(s.leadMin)||!Number.isInteger(s.leadMax)||s.leadMin<0||s.leadMax<s.leadMin||!['disabled','waitlist','enabled'].includes(s.internationalMode))throw new Error('invalid_settings');for(const t of s.templates){l10n.parse(t.subject);l10n.parse(t.body);l10n.parse(t.providerTemplate)}result=await rpc('thuraya_save_settings',{p_settings:readiness(s),p_actor:u.id});break}
case 'save-private':{const u=await requireRole(req,'settings');const v=z.object({productId:id,supplierSku:text,supplierReference:text,cost:z.number().int().nonnegative().nullable(),notes:text}).strict().parse(p.value);result=await rpc('thuraya_private_write',{p_action:'product',p_value:snake(v),p_actor:u.id});break}
case 'retry-notification':{const u=await requireRole(req,'notifications');result=await rpc('thuraya_private_write',{p_action:'retry',p_value:{id:id.parse(p.id)},p_actor:u.id});break}
case 'reconcile-notification':{const u=await requireRole(req,'notifications');if(!['owner','admin'].includes(u.role))throw new Error('forbidden');const input=z.object({id,receipt:z.string().regex(/^[A-Za-z0-9._:/=-]{1,200}$/),confirmed:z.literal(true)}).strict().parse(p);result=await rpc('thuraya_reconcile_notification',{p_id:input.id,p_receipt:input.receipt,p_actor:u.id});break}
case 'media-cleanup-status':{await requireRole(req,'media');result=await rpc<MediaCleanupJob[]>('thuraya_media_cleanup_status');break}
case 'retry-media-cleanup':{const u=await requireRole(req,'media');const input=z.object({bucket:z.enum(['product-media','review-media']),path:z.string().min(1).max(512)}).strict().parse(p);result=await rpc('thuraya_retry_media_cleanup',{p_bucket:input.bucket,p_path:input.path,p_actor:u.id});break}
case 'save-profile':{const u=await requireCustomer(req);const v=z.object({name:z.string().trim().min(1).max(100),phone:z.string().max(30),locale:z.enum(['ar','he','en']),emailUpdates:z.boolean(),whatsappUpdates:z.boolean(),marketingConsent:z.boolean()}).strict().parse(p.value);const {error}=await db.from('profiles').update(snake(v)).eq('id',u.id);if(error)throw error;break}
case 'addresses':{const u=await requireCustomer(req);const {data,error}=await db.from('addresses').select('*').eq('customer_id',u.id).order('is_default',{ascending:false}).order('id');if(error)throw error;result=data.map(a=>({id:a.id,customerId:a.customer_id,firstName:a.first_name,lastName:a.last_name,phone:a.phone,city:a.city,street:a.street,postalCode:a.postal_code,country:a.country,isDefault:a.is_default}));break}
case 'save-address':{const u=await requireCustomer(req);const v=z.object({id,firstName:checkoutSchema.shape.firstName,lastName:checkoutSchema.shape.lastName,phone:checkoutSchema.shape.phone,city:checkoutSchema.shape.city,street:checkoutSchema.shape.street,postalCode:checkoutSchema.shape.postalCode,country:z.literal('IL'),isDefault:z.boolean().default(false)}).strict().parse(p.value);result=await rpc('thuraya_save_address',{p_customer:u.id,p_address:snake(v)});break}
case 'delete-address':{const u=await requireCustomer(req);result=await rpc('thuraya_delete_address',{p_customer:u.id,p_id:id.parse(p.id)});break}
case 'set-wishlist':{const u=await requireCustomer(req);const ids=z.array(id).max(100).parse(p.ids);result=await rpc('thuraya_set_wishlist',{p_customer:u.id,p_ids:ids});break}
case 'merge-wishlist':{const u=await requireCustomer(req);const ids=z.array(id).max(100).parse(p.ids);if(ids.length){const {error}=await db.from('wishlists').upsert(ids.map(product_id=>({customer_id:u.id,product_id})),{onConflict:'customer_id,product_id',ignoreDuplicates:true});if(error)throw error}const {data}=await db.from('wishlists').select('product_id').eq('customer_id',u.id);result=data?.map(x=>x.product_id)||[];break}
case 'inquiry':{const v=z.object({productId:id.nullable(),name:z.string().trim().min(2).max(100),email:z.string().email().max(254),phone:z.string().max(30),message:z.string().trim().min(5).max(2000),locale:z.enum(['ar','he','en']),turnstileToken:z.string().optional()}).parse(p);await antiAbuse(v.turnstileToken);result=await rpc('thuraya_private_write',{p_action:'inquiry',p_value:v,p_actor:null});break}
case 'review':{const u=await identity(req);const v=z.object({productId:id,name:z.string().trim().min(2).max(100),rating:z.number().int().min(1).max(5).nullable(),text:z.string().trim().max(2000),media:z.array(z.string()).max(0),turnstileToken:z.string().max(4096).optional()}).parse(p);await antiAbuse(v.turnstileToken);if(v.rating===null&&!v.text)throw new Error('invalid_review');const orders=u?await rpc<{status:string;items:{productId:string}[]}[]>('thuraya_customer_orders',{p_customer:u.id}):[];const uploadKey=crypto.randomUUID()+crypto.randomUUID();const reviewId=await rpc<string>('thuraya_create_review',{p:v,p_hash:await hashValue(uploadKey,env('TRACKING_HASH_SECRET')),p_customer:u?.id??null,p_verified:orders.some(o=>o.status==='delivered'&&o.items.some(i=>i.productId===v.productId))});result={reviewId,uploadKey};break}
case 'review-upload-ticket':{await rate(req,'review-photo-reserve',6);const v=z.object({reviewId:id,uploadKey:z.string().length(72),name:z.string().max(200),mime:z.string(),bytes:z.number().int()}).parse(p);if(!reviewPhotoAllowed(v.mime,v.bytes,v.name))throw new Error('invalid_upload');const path=v.reviewId+'/'+crypto.randomUUID()+'.'+v.name.split('.').at(-1)!.toLowerCase();await rpc('thuraya_review_upload',{p_review:v.reviewId,p_hash:await hashValue(v.uploadKey,env('TRACKING_HASH_SECRET')),p_action:'reserve',p_path:path,p_mime:v.mime,p_bytes:v.bytes});const {data,error}=await db.storage.from('review-media').createSignedUploadUrl(path);if(error||!data)throw new Error('invalid_upload');result={path,token:data.token};break}
case 'review-upload-confirm':{const v=z.object({reviewId:id,uploadKey:z.string().length(72),path:z.string().max(512)}).parse(p);const args={p_review:v.reviewId,p_hash:await hashValue(v.uploadKey,env('TRACKING_HASH_SECRET')),p_path:v.path};const ticket=await rpc<{mime:string;bytes:number}>('thuraya_review_upload',{...args,p_action:'check'});const {data:blob,error}=await db.storage.from('review-media').download(v.path);if(error||!blob||blob.size!==ticket.bytes||blob.type!==ticket.mime||!matchesMagic(new Uint8Array(await blob.slice(0,32).arrayBuffer()),ticket.mime))throw new Error('invalid_upload');await rpc('thuraya_review_upload',{...args,p_action:'confirm'});break}
case 'upload-ticket':{const u=await requireRole(req,'media');const v=z.object({name:z.string().max(200),mime:z.string().max(100),bytes:z.number().int()}).parse(p);if(!mediaAllowed(v.mime,v.bytes,v.name))throw new Error('invalid_media');const path=`${u.id}/${crypto.randomUUID()}.${v.name.split('.').at(-1)?.toLowerCase()}`;await rpc('thuraya_private_write',{p_action:'upload-ticket',p_value:{path,mime:v.mime,bytes:v.bytes},p_actor:u.id});const {data,error}=await db.storage.from('product-media').createSignedUploadUrl(path);if(error)throw error;result={path,token:data.token};break}
case 'confirm-upload':{const u=await requireRole(req,'media');const path=z.string().max(512).parse(p.path);const ticket=await rpc<{mime:string;bytes:number;created_at:string}|null>('thuraya_private_write',{p_action:'upload-check',p_value:{path},p_actor:u.id});if(!ticket||Date.parse(ticket.created_at)<Date.now()-7200000)throw new Error('invalid_upload');const {data:blob,error}=await db.storage.from('product-media').download(path);if(error||!blob||blob.size!==ticket.bytes||blob.type!==ticket.mime||!matchesMagic(new Uint8Array(await blob.slice(0,32).arrayBuffer()),ticket.mime))throw new Error('invalid_upload');await rpc('thuraya_private_write',{p_action:'upload-confirm',p_value:{path},p_actor:u.id});const {data}=await db.storage.from('product-media').createSignedUrl(path,3600);result={src:data?.signedUrl};break}
case 'delete-media':{const u=await requireRole(req,'media');const mid=id.parse(p.id);const {data:m}=await db.from('media').select('storage_path').eq('id',mid).single();await rpc('thuraya_private_write',{p_action:'delete-media',p_value:{id:mid},p_actor:u.id});let storageCleanup:'not_applicable'|'removed'|'queued'='not_applicable';if(m?.storage_path){let queued=false;try{queued=await rpc<boolean>('thuraya_queue_media_cleanup',{p_bucket:'product-media',p_path:m.storage_path})}catch{/* existing orphan collector remains the safe fallback */}const {error}=await db.storage.from('product-media').remove([m.storage_path]);if(error){storageCleanup='queued';if(queued)try{await rpc('thuraya_cleanup_result',{p_bucket:'product-media',p_path:m.storage_path,p_success:false})}catch{/* cleanup remains queued */}}else{storageCleanup='removed';if(queued)try{await rpc('thuraya_cleanup_result',{p_bucket:'product-media',p_path:m.storage_path,p_success:true})}catch{/* object is already gone */}}}result={storageCleanup};break}
default:throw new Error('unknown_action')}
return respond(req,result)}catch(e){return respond(req,{error:safeError(e)},e instanceof Error&&['forbidden','unauthorized','mfa_required'].includes(e.message)?403:400)}});
