import {adminMutation} from '../../shared/admin-mutation';
import {settingsSchema} from '../../shared/settings-schema';
import {shippingZoneSchema,shipsTo,shippingEta,assertShippingProducts} from '../../shared/shipping';
import {demoCredentials} from '../demoCredentials';
import {mediaIsReferenced} from '../../shared/media-references';
import {customerCatalog} from '../../shared/public-data';
import {mediaDimensions} from './media';
import {reviewPhotoAllowed,REVIEW_PHOTO_LIMIT} from '../../shared/review-media';
import {matchesMagic} from '../../shared/security';
import {newId} from '../../shared/id';
import {createClient,type SupabaseClient} from '@supabase/supabase-js';
import type {AdminData,AdminOrder,Address,CartLine,Catalog,CheckoutInput,Customer,Order,OrderStatus,Product,Role,Review,Inquiry,Media,MediaCleanupJob} from '../../shared/domain';
import {can,cartPrice,assertTransition,publicationErrors,publicOrder,normalizeContact,canRetry,mediaAllowed,validateDiscount} from '../../shared/logic';
import {checkoutSchema} from '../../shared/validation';
import {config} from '../config';
import {initialData} from '../seed';
const key='thuraya.demo.v1';
const sessionKey='thuraya.demo.session';
const read=():AdminData=>{const raw=localStorage.getItem(key);if(raw){try{return JSON.parse(raw) as AdminData}catch{/* reset corrupt local demo only */}}const d=initialData(true);localStorage.setItem(key,JSON.stringify(d));return d};
const write=(d:AdminData)=>localStorage.setItem(key,JSON.stringify(d));
let sb:SupabaseClient|null=null;
export function supabase(){if(!config.supabaseUrl||!config.supabaseKey)throw new Error('backend_not_configured');return sb??=createClient(config.supabaseUrl,config.supabaseKey)}
export async function invoke<T>(action:string,payload:unknown={}):Promise<T>{const {data,error}=await supabase().functions.invoke('store-api',{body:{action,payload}});if(error||data?.error){let message=data?.error;try{if(!message&&error&&'context' in error)message=(await error.context.json()).error}catch{/* safe fallback */}throw new Error(message||'request_failed')};return data as T}
const demoCustomer=(email:string,role:Role):Customer=>({id:`demo-${role}`,email,name:role==='customer'?'Demo customer':'Demo owner',phone:'',role,locale:'en',emailUpdates:true,whatsappUpdates:false,marketingConsent:false});
export async function session():Promise<Customer|null>{if(config.demo){const raw=sessionStorage.getItem(sessionKey);return raw?JSON.parse(raw) as Customer:null}if(!config.supabaseUrl)return null;const {data}=await supabase().auth.getSession();if(!data.session)return null;const {data:p,error}=await supabase().from('profiles').select('id,email,name,phone,role,locale,email_updates,whatsapp_updates,marketing_consent').eq('id',data.session.user.id).single();if(error)throw error;return {...p,emailUpdates:p.email_updates,whatsappUpdates:p.whatsapp_updates,marketingConsent:p.marketing_consent} as Customer}
export async function signIn(email:string,password:string){if(config.demo){const roles:Record<string,Role>={[demoCredentials.owner]:'owner',[demoCredentials.customer]:'customer',[demoCredentials.orders]:'order_manager',[demoCredentials.content]:'content_manager'};const role=roles[email];if(!role||password!==demoCredentials.password)throw new Error('invalid_credentials');const c=demoCustomer(email,role);sessionStorage.setItem(sessionKey,JSON.stringify(c));const d=read();if(!d.customers.some(x=>x.id===c.id)){d.customers.push(c);write(d)}return c}const {error}=await supabase().auth.signInWithPassword({email,password});if(error)throw error;return session()}
export async function register(email:string,password:string,name:string){if(config.demo)throw new Error('Use the listed local demo accounts.');const {error}=await supabase().auth.signUp({email,password,options:{data:{name},emailRedirectTo:`${location.origin}/en/account`}});if(error)throw error}
export async function signOut(){if(config.demo)sessionStorage.removeItem(sessionKey);else await supabase().auth.signOut()}
export async function resetPassword(email:string){if(config.demo)return;await supabase().auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/en/account/reset`})}
export async function updatePassword(password:string){const {error}=await supabase().auth.updateUser({password});if(error)throw error}
export async function catalog():Promise<Catalog>{if(!config.demo){if(!config.supabaseUrl){const d=initialData();return customerCatalog({...d,products:[],reviews:[],pages:d.pages.filter(p=>p.status==='published'&&(p.kind!=='policy'||p.legalReviewed))})}return invoke<Catalog>('catalog')}const d=read();return customerCatalog({...d,products:d.products.filter(p=>p.status==='published'&&(!p.publishAt||Date.parse(p.publishAt)<=Date.now())),reviews:d.reviews.filter(r=>r.status==='approved'),pages:d.pages.filter(p=>p.status==='published'&&(p.kind!=='policy'||p.legalReviewed))})}
async function guard(area:string){const c=await session();if(!c||!can(c.role,area))throw new Error('forbidden');return c}
export async function adminData():Promise<AdminData>{if(!config.demo)return invoke('admin-data');await guard('dashboard');return read()}
export type Entity='products'|'categories'|'collections'|'sections'|'zones'|'pages'|'inquiries'|'discounts'|'reviews'|'media';
const areas:Record<Entity,string>={products:'products',categories:'categories',collections:'collections',sections:'content',zones:'shipping',pages:'content',inquiries:'inquiries',discounts:'promotions',reviews:'reviews',media:'media'};
export async function reorderSections(ids:string[]){if(!config.demo)return invoke('reorder-sections',{ids});const c=await guard('content');const d=read();if(ids.length!==d.sections.length||new Set(ids).size!==ids.length||ids.some(id=>!d.sections.some(s=>s.id===id)))throw new Error('Stale section order');d.sections.forEach(s=>{s.position=ids.indexOf(s.id)});d.audit.unshift({id:newId(),actor:c.email,action:'reorder_sections',target:'homepage',at:new Date().toISOString(),summary:'Section order updated'});write(d)}
export async function reorderTaxonomy(entity:'categories'|'collections',ids:string[]){if(!config.demo)return invoke('reorder-taxonomy',{entity,ids});const c=await guard('content');const d=read();const rows=d[entity];if(ids.length!==rows.length||new Set(ids).size!==ids.length||ids.some(id=>!rows.some(row=>row.id===id)))throw new Error('Stale taxonomy order');rows.forEach(row=>{row.position=ids.indexOf(row.id)});d.audit.unshift({id:newId(),actor:c.email,action:`reorder_${entity}`,target:entity,at:new Date().toISOString(),summary:'Taxonomy order updated'});write(d)}
export async function saveEntity(entity:Entity,value:AdminData[Entity][number],override=false){if(!config.demo)return invoke('save-entity',{entity,value:adminMutation(entity,value),override});const c=await guard(areas[entity]);if(entity==='products'){const p=value as Product;if(p.status==='published'){const errs=publicationErrors(p,override&&c.role==='owner');if(errs.length)throw new Error(errs.join('\n'))}}if(entity==='zones')shippingZoneSchema.parse(value);if(entity==='discounts')validateDiscount(value as AdminData['discounts'][number]);const d=read();const rows=d[entity] as {id:string}[];const i=rows.findIndex(r=>r.id===value.id);if(i<0)rows.push(value);else rows[i]=value;d.audit.unshift({id:newId(),actor:c.email,action:`save_${entity}`,target:value.id,at:new Date().toISOString(),summary:'Record updated'});write(d)}
export async function saveSettings(settings:AdminData['settings']){if(!config.demo)return invoke('save-settings',{settings});await guard('settings');settings=settingsSchema.parse(settings);const d=read();d.settings=settings;write(d)}
export async function savePrivate(value:AdminData['privateProducts'][number]){if(!config.demo)return invoke('save-private',{value});await guard('settings');const d=read();d.privateProducts=d.privateProducts.filter(p=>p.productId!==value.productId).concat(value);write(d)}
export async function placeOrder(input:CheckoutInput):Promise<Order>{const valid=checkoutSchema.parse(input);if(!config.demo)return invoke('place-order',valid);const idkey=`thuraya.demo.idem.${valid.idempotencyKey}`;const previous=localStorage.getItem(idkey);const d=read();if(previous){const o=d.orders.find(x=>x.id===previous);if(o)return publicOrder(o)}const z=d.zones.find(z=>z.id===valid.zoneId&&shipsTo(z,valid.country,valid.city));if(!z)throw new Error('shipping_unavailable');const payment=d.settings.paymentMethods.find(p=>p.id===valid.paymentMethod&&p.enabled&&p.ready);if(!payment||!d.settings.checkoutEnabled)throw new Error('checkout_unavailable');const discount=valid.discountCode?d.discounts.find(x=>x.code.toUpperCase()===valid.discountCode.toUpperCase()):undefined;if(valid.discountCode&&!discount)throw new Error('discount_unavailable');const subtotal=cartPrice(valid.lines,d.products,0).subtotal;const shipping=d.settings.freeShippingThreshold!==null&&subtotal>=d.settings.freeShippingThreshold?0:z.price;const totals=cartPrice(valid.lines,d.products,shipping,discount);const c=await session();const at=new Date().toISOString();const o:AdminOrder={id:newId(),number:`TH-${newId().slice(0,12).replaceAll('-','').toUpperCase()}`,customerId:c?.id??null,locale:valid.locale,status:'payment_pending',paymentStatus:'pending',paymentMethod:valid.paymentMethod,items:valid.lines.map(l=>{const p=d.products.find(p=>p.id===l.productId)!;const v=p.variants.find(v=>v.id===l.variantId)!;const unitPrice=p.basePrice!+v.adjustment;return {productId:p.id,variantId:v.id,sku:v.sku,name:p.name,image:p.media[0]?.src||'',options:p.axes.map(a=>a.values.find(x=>x.id===v.options[a.id])!.label),gem:{...p.gem,...v.gem},metal:{...p.metal,...v.metal},measurements:{...p.measurements,...v.measurements},quantity:l.quantity,unitPrice,lineTotal:unitPrice*l.quantity}}),...totals,createdAt:at,...shippingEta(valid.lines,d.products,d.settings,z),events:[{id:newId(),status:'order_received',at},{id:newId(),status:'payment_pending',at}],safeTrackingUrl:null,isDemo:true,customer:valid,internalNotes:'',supplierReference:''};d.orders.unshift(o);if(discount)discount.used++;for(const l of valid.lines){const v=d.products.find(p=>p.id===l.productId)!.variants.find(v=>v.id===l.variantId)!;if(v.stock!==null)v.stock-=l.quantity}enqueue(d,o);write(d);localStorage.setItem(idkey,o.id);return publicOrder(o)}
function enqueue(d:AdminData,o:AdminOrder){const event=o.events.at(-1)!;for(const audience of ['owner','customer'] as const)for(const channel of ['email','whatsapp'] as const){if(audience==='owner'&&channel==='whatsapp')continue;if(d.notifications.some(n=>n.eventId===event.id&&n.channel===channel&&n.audience===audience))continue;d.notifications.push({id:newId(),eventId:event.id,orderId:o.id,channel,audience,templateId:`${event.status}-${channel}`,locale:o.locale,status:'disabled',attempts:0,providerId:null,sentAt:null,error:'Local demo: no external messages are sent.',nextAttemptAt:null})}}
export async function changeOrder(id:string,status:OrderStatus){if(!config.demo)return invoke('change-order',{id,status});await guard('orders');const d=read();const o=d.orders.find(x=>x.id===id);if(!o)throw new Error('not_found');assertTransition(o.status,status);o.status=status;if(status==='payment_confirmed')o.paymentStatus='paid';if(status==='refunded')o.paymentStatus='refunded';o.events.push({id:newId(),status,at:new Date().toISOString()});enqueue(d,o);write(d)}
export async function updateOrderDetails(id:string,patch:{internalNotes?:string;supplierReference?:string;safeTrackingUrl:string|null;etaMin:number;etaMax:number}){if(!config.demo)return invoke('update-order',{id,patch});const c=await guard('orders');if((patch.internalNotes!==undefined||patch.supplierReference!==undefined)&&!['owner','admin'].includes(c.role))throw new Error('forbidden');if(patch.safeTrackingUrl&&!patch.safeTrackingUrl.startsWith('https://'))throw new Error('HTTPS required');const d=read();const o=d.orders.find(x=>x.id===id);if(!o)throw new Error('not_found');Object.assign(o,patch);write(d)}
export async function trackOrder(number:string,contact:string):Promise<Order|null>{if(!config.demo)return invoke('track-order',{number,contact});const o=read().orders.find(x=>x.number===number.trim().toUpperCase());return o&&[o.customer.email,o.customer.phone].some(x=>normalizeContact(x)===normalizeContact(contact))?publicOrder(o):null}
export async function customerOrders(){if(!config.demo)return invoke<Order[]>('customer-orders');const c=await session();return read().orders.filter(o=>o.customerId===c?.id).map(publicOrder)}
export async function saveProfile(value:Customer){const payload={name:value.name,phone:value.phone,locale:value.locale,emailUpdates:value.emailUpdates,whatsappUpdates:value.whatsappUpdates,marketingConsent:value.marketingConsent};if(!config.demo)return invoke('save-profile',{value:payload});const c=await session();if(!c||c.id!==value.id)throw new Error('forbidden');const safe={...c,...payload};sessionStorage.setItem(sessionKey,JSON.stringify(safe));const d=read();d.customers=d.customers.filter(x=>x.id!==c.id).concat(safe);write(d)}
export async function addresses(){if(!config.demo)return invoke<Address[]>('addresses');const c=await session();if(!c)return [];let rows:Address[]=[];try{const raw=JSON.parse(localStorage.getItem(`thuraya.demo.addresses.${c.id}`)||'[]');if(Array.isArray(raw))rows=raw.filter((a):a is Address=>!!a&&typeof a==='object'&&typeof a.id==='string'&&typeof a.street==='string').map(a=>({...a,customerId:c.id,isDefault:a.isDefault===true}))}catch{/* corrupt demo addresses are ignored */}if(rows.length&&!rows.some(a=>a.isDefault))rows[0]={...rows[0],isDefault:true};return rows.sort((a,b)=>Number(b.isDefault)-Number(a.isDefault)||a.id.localeCompare(b.id))}
export async function saveAddress(a:Address){if(!config.demo)return invoke('save-address',{value:{id:a.id,firstName:a.firstName,lastName:a.lastName,phone:a.phone,city:a.city,street:a.street,postalCode:a.postalCode,country:a.country,isDefault:a.isDefault}});const c=await session();if(!c||a.customerId!==c.id)throw new Error('forbidden');const rows=await addresses();const target={...a,customerId:c.id,isDefault:a.isDefault||!rows.some(x=>x.isDefault)};const next=rows.filter(x=>x.id!==a.id).map(x=>target.isDefault?{...x,isDefault:false}:x).concat(target);localStorage.setItem(`thuraya.demo.addresses.${c.id}`,JSON.stringify(next))}
export async function deleteAddress(id:string){if(!config.demo)return invoke('delete-address',{id});const c=await session();if(!c)throw new Error('forbidden');const rows=await addresses();const target=rows.find(a=>a.id===id);if(!target)throw new Error('not_found');const next=rows.filter(a=>a.id!==id);if(target.isDefault&&next.length)next[0]={...next[0],isDefault:true};localStorage.setItem(`thuraya.demo.addresses.${c.id}`,JSON.stringify(next))}
export async function mergeWishlist(ids:string[]){if(!config.demo)return invoke<string[]>('merge-wishlist',{ids});const c=await session();if(!c)return ids;const k=`thuraya.demo.wishlist.${c.id}`;const merged=[...new Set([...(JSON.parse(localStorage.getItem(k)||'[]') as string[]),...ids])];localStorage.setItem(k,JSON.stringify(merged));return merged}
export async function submitInquiry(i:Omit<Inquiry,'id'|'status'|'createdAt'>&{turnstileToken?:string}){if(!config.demo)return invoke('inquiry',i);if(i.name.length<2||!i.email.includes('@')||i.message.length<5||i.message.length>2000)throw new Error('invalid');const d=read();d.inquiries.unshift({...i,id:newId(),status:'open',createdAt:new Date().toISOString()});write(d)}
export async function submitReview(r:Pick<Review,'productId'|'name'|'rating'|'text'|'media'>&{turnstileToken?:string},photos:File[]=[]):Promise<{failedPhotos:number}>{if(photos.length>REVIEW_PHOTO_LIMIT)throw new Error('invalid_upload');for(const f of photos){if(!reviewPhotoAllowed(f.type,f.size,f.name)||!matchesMagic(new Uint8Array(await f.slice(0,32).arrayBuffer()),f.type))throw new Error('invalid_upload');await mediaDimensions(f)}if(!config.demo){const receipt=await invoke<{reviewId:string;uploadKey:string}>('review',{...r,media:[]});let failedPhotos=0;for(const f of photos){try{const ticket=await invoke<{path:string;token:string}>('review-upload-ticket',{...receipt,name:f.name,mime:f.type,bytes:f.size});const {error}=await supabase().storage.from('review-media').uploadToSignedUrl(ticket.path,ticket.token,f,{contentType:f.type});if(error)throw error;await invoke('review-upload-confirm',{...receipt,path:ticket.path})}catch{failedPhotos++}}return {failedPhotos}}if(!r.text.trim()&&r.rating===null)throw new Error('invalid');const d=read();const c=await session();const media=await Promise.all(photos.map(f=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(f)})));d.reviews.push({...r,media,id:newId(),customerId:c?.id??null,verified:!!c&&d.orders.some(o=>o.customerId===c.id&&o.status==='delivered'&&o.items.some(i=>i.productId===r.productId)),status:'pending',createdAt:new Date().toISOString()});write(d);return {failedPhotos:0}}
export async function retryNotification(id:string){if(!config.demo)return invoke('retry-notification',{id});await guard('notifications');const d=read();const n=d.notifications.find(x=>x.id===id);if(!n||!canRetry(n))throw new Error('not_retryable');n.status='disabled';n.error='Local demo: no provider called';write(d)}
export async function reconcileNotification(id:string,receipt:string,confirmed:boolean){if(config.demo)throw new Error('Local demo cannot attest external provider acceptance');return invoke('reconcile-notification',{id,receipt,confirmed})}
export async function mediaCleanupStatus():Promise<MediaCleanupJob[]>{if(config.demo)return [];return invoke<MediaCleanupJob[]>('media-cleanup-status')}
export async function retryMediaCleanup(bucket:MediaCleanupJob['bucket'],path:string){if(config.demo)throw new Error('Local demo has no storage cleanup queue');return invoke('retry-media-cleanup',{bucket,path})}
export async function upload(file:File):Promise<Media>{if(!mediaAllowed(file.type,file.size,file.name))throw new Error('Use JPEG, PNG, WebP, AVIF, MP4 or PDF up to 20 MB.');await guard('media');const dimensions=await mediaDimensions(file);const id=newId();let src:string;let storagePath:string|undefined;if(config.demo){src=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file)})}else{const ticket=await invoke<{path:string;token:string}>('upload-ticket',{name:file.name,mime:file.type,bytes:file.size});storagePath=ticket.path;const {error}=await supabase().storage.from('product-media').uploadToSignedUrl(ticket.path,ticket.token,file,{contentType:file.type});if(error)throw error;const checked=await invoke<{src:string}>('confirm-upload',{path:ticket.path,mime:file.type,bytes:file.size});src=checked.src}const m:Media={id,src,storagePath,alt:{en:file.name,ar:'',he:''},kind:file.type==='video/mp4'?'video':file.type==='application/pdf'?'certificate':'image',...dimensions,position:0,mime:file.type,bytes:file.size};await saveEntity('media',m);return m}
export async function deleteMedia(id:string){if(!config.demo)return invoke('delete-media',{id});await guard('media');const d=read();if(d.media.some(m=>m.id===id&&mediaIsReferenced(d,m)))throw new Error('Media is in use');d.media=d.media.filter(m=>m.id!==id);write(d)}
export async function quote(lines:CartLine[],zoneId:string,code:string,city:string){if(!config.demo)return invoke<ReturnType<typeof cartPrice>>('quote',{lines,zoneId,code,city,country:'IL'});const d=read();const z=d.zones.find(z=>z.id===zoneId&&shipsTo(z,'IL',city));if(!z)throw new Error('shipping_unavailable');assertShippingProducts(lines,d.products,'IL');const dis=code?d.discounts.find(x=>x.code.toUpperCase()===code.toUpperCase()):undefined;if(code&&!dis)throw new Error('discount_unavailable');const subtotal=cartPrice(lines,d.products,0).subtotal;return cartPrice(lines,d.products,d.settings.freeShippingThreshold!==null&&subtotal>=d.settings.freeShippingThreshold?0:z.price,dis)}
