import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {words} from '../../src/i18n';
import {formatMoney} from '../../shared/logic';
for(const locale of ['ar','he','en'] as const){
for(const width of [390,430,820,1440])test(`${locale} ${width}px homepage and no overflow`,async({page})=>{await page.setViewportSize({width,height:900});await page.goto(`/${locale}`);await expect(page.locator('html')).toHaveAttribute('dir',locale==='en'?'ltr':'rtl');await expect(page.getByRole('heading',{level:1})).toContainText(words.hero[locale]);await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:`test-results/${locale}-${width}.png`,fullPage:true})});
test(`${locale} product variants, size and cart persistence`,async({page})=>{await page.goto(`/${locale}/product/demo-polaris-necklace`);const options=page.locator('.variant-options button');await options.last().click();await expect(options.last()).toHaveAttribute('aria-pressed','true');await expect(page.locator('.product-price')).toContainText(formatMoney(74000,locale));await page.getByRole('button',{name:words.size[locale],exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await page.locator('.purchase-row').getByRole('button',{name:words.add[locale],exact:true}).click();await expect(page.getByRole('dialog')).toContainText(formatMoney(74000,locale));await page.reload();await page.goto(`/${locale}/cart`);await expect(page.locator('.cart-line')).toHaveCount(1)});
test(`${locale} search filters and zero state`,async({page})=>{await page.goto(`/${locale}/shop?q=Zenit`);await expect(page.locator('.product-card')).toHaveCount(1);await page.getByPlaceholder(words.search[locale],{exact:true}).fill('no-match-test');await expect(page.getByRole('heading',{name:words.noResults[locale]})).toBeVisible()});
test(`${locale} guest tracking generic error`,async({page})=>{await page.goto(`/${locale}/track`);await page.getByLabel(words.orderNumber[locale],{exact:true}).fill('TH-NONEXISTENT');await page.getByLabel(words.trackingContact[locale],{exact:true}).fill('nobody@example.test');await page.getByRole('button',{name:words.track[locale],exact:true}).click();await expect(page.getByRole('alert')).toHaveText(words.trackError[locale])});
test(`${locale} accessibility baseline`,async({page})=>{await page.goto(`/${locale}`);await expect(page.getByRole('heading',{level:1})).toBeVisible();const results=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();expect(results.violations).toEqual([])});
}
test('language switching preserves product',async({page})=>{await page.goto('/en/product/demo-vega');await page.getByRole('button',{name:'Change language',exact:true}).click();await page.getByRole('menuitemradio',{name:'עברית',exact:true}).click();await expect(page).toHaveURL(/\/he\/product\/demo-vega/);await expect(page.locator('html')).toHaveAttribute('dir','rtl')});
test('checkout validates required fields and no prechecked consent',async({page})=>{await page.goto('/en/product/demo-nova');await page.locator('.purchase-row').getByRole('button',{name:'Add to bag',exact:true}).click();await page.getByRole('link',{name:'Continue to checkout',exact:true}).click();await expect(page.locator('input[type=checkbox]').first()).not.toBeChecked();await page.getByRole('button',{name:words.place.en,exact:true}).click();await expect(page.locator('[aria-invalid=true]').first()).toBeVisible()});
test('customer cannot use owner console',async({page})=>{await page.goto('/admin');await page.getByLabel('Email',{exact:true}).fill('customer@thuraya.test');await page.getByLabel('Password',{exact:true}).fill('ThurayaDemo!2026');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Insufficient permissions')});
test('owner sees real drafts and notification state',async({page})=>{await page.goto('/admin');await page.getByLabel('Email',{exact:true}).fill('owner@thuraya.test');await page.getByLabel('Password',{exact:true}).fill('ThurayaDemo!2026');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByText('Welcome to your atelier.')).toBeVisible();await page.getByRole('link',{name:'Products',exact:true}).click();await expect(page.getByText('TH-DRAFT-1',{exact:true})).toBeVisible()});
test('unknown route shows localized not found',async({page})=>{await page.goto('/he/no-such-page');await expect(page.getByRole('heading',{name:words.notFound.he})).toBeVisible()});
