import {createClient} from '@supabase/supabase-js';
import {can} from '../../../shared/logic.ts';
import {hashValue} from '../../../shared/security.ts';
import {paymentReadiness} from '../../../shared/payment-readiness.ts';
import type {Role,Settings} from '../../../shared/domain.ts';
export const env=(key:string)=>Deno.env.get(key)||'';
export const db=createClient(env('SUPABASE_URL'),env('SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false,autoRefreshToken:false}});
export async function rpc<T=unknown>(name:string,args:Record<string,unknown>={}):Promise<T>{const {data,error}=await db.rpc(name,args);if(error)throw new Error(error.message);return data as T}
export async function settings():Promise<Settings>{const {data,error}=await db.from('store_settings').select('config').single();if(error||!data)throw new Error('store_not_configured');return data.config as Settings}
export function readiness(s:Settings):Settings{return {...s,paymentMethods:s.paymentMethods.map(m=>({...m,ready:paymentReadiness(m,env('BANK_TRANSFER_ACCOUNT_CONFIRMED')==='true').ready}))}}
export async function identity(req:Request){const token=(req.headers.get('authorization')||'').replace(/^Bearer /i,'');if(!token||token===env('SUPABASE_ANON_KEY'))return null;const {data,error}=await db.auth.getUser(token);if(error||!data.user)return null;const {data:p,error:e}=await db.from('profiles').select('id,role,email').eq('id',data.user.id).single();if(e||!p)return null;return {...p,token,role:p.role as Role}}
export async function requireRole(req:Request,area:string){const p=await identity(req);if(!p||!can(p.role,area))throw new Error('forbidden');const s=await settings();if(s.requireMfa){const {data,error}=await db.auth.getClaims(p.token);if(error||data?.claims?.aal!=='aal2')throw new Error('mfa_required')}return p}
export async function requireCustomer(req:Request){const p=await identity(req);if(!p)throw new Error('unauthorized');return p}
export async function rate(req:Request,action:string,limit=20){const ip=req.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||'unknown';const key=await hashValue(`${action}:${ip}`,env('TRACKING_HASH_SECRET'));if(!await rpc('thuraya_rate_limit',{p_key:key,p_limit:limit,p_seconds:60}))throw new Error('rate_limited')}
export async function antiAbuse(token?:string){if(!env('TURNSTILE_SECRET_KEY'))return;const r=await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'POST',body:new URLSearchParams({secret:env('TURNSTILE_SECRET_KEY'),response:token||''}),signal:AbortSignal.timeout(10000)});const d=await r.json();if(!r.ok||d.success!==true||env('TURNSTILE_HOSTNAME')&&d.hostname!==env('TURNSTILE_HOSTNAME'))throw new Error('verification_required')}
export function headers(req:Request){const origin=req.headers.get('origin')||'';const allowed=env('ALLOWED_ORIGINS').split(',').filter(Boolean);return {'Content-Type':'application/json','Cache-Control':'no-store','Vary':'Origin','Access-Control-Allow-Origin':allowed.includes(origin)?origin:env('SITE_URL'),'Access-Control-Allow-Headers':'authorization,apikey,content-type,x-client-info','Access-Control-Allow-Methods':'POST,OPTIONS','X-Content-Type-Options':'nosniff'}}
export function respond(req:Request,value:unknown,status=200){return new Response(JSON.stringify(value??null),{status,headers:headers(req)})}
export function safeError(e:unknown){const message=e instanceof Error?e.message:'';const allowed=['forbidden','unauthorized','mfa_required','rate_limited','verification_required','idempotency_conflict','checkout_unavailable','payment_unavailable','shipping_unavailable','discount_unavailable','invalid_transition','provider_confirmation_required','stock','not_retryable','unavailable','publication_incomplete','translation_incomplete','media_in_use','media_cleanup_pending','cleanup_not_found','stale_section_order','stale_taxonomy_order'];return allowed.includes(message)?message:'request_failed'}
export const snake=(v:Record<string,unknown>)=>Object.fromEntries(Object.entries(v).map(([k,x])=>[k.replace(/[A-Z]/g,c=>'_'+c.toLowerCase()),x]));
