import {Fragment,useEffect,useRef,type ReactNode} from 'react';
import {Link} from 'react-router-dom';
import {X,Heart,ArrowUpRight} from 'lucide-react';
import type {Media,Product} from '../../shared/domain';
import {formatMoney,variantPrice} from '../../shared/logic';
import {useStore} from '../store';
import {t} from '../i18n';
import {analytics} from '../services/analytics';
import {splitLatinRuns} from './bidi';
import {browseMedia} from '../../shared/media-roles';
export function Modal({open,onClose,title,children,drawer=false,className=''}:{open:boolean;onClose:()=>void;title:string;children:ReactNode;drawer?:boolean;className?:string}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const d=ref.current;if(open&&!d?.open){d?.showModal();document.body.style.overflow='hidden'}else if(!open&&d?.open)d.close();return()=>{document.body.style.overflow=''}},[open]);return <dialog className={`${drawer?'drawer':'modal'} ${className}`.trim()} ref={ref} onCancel={onClose} onClose={onClose} onClick={e=>{if(e.target===ref.current)onClose()}} aria-label={title}><div className="dialog-head"><h2>{title}</h2><button className="icon" onClick={onClose} aria-label={t(useStore().locale,'close')}><X size={20} strokeWidth={1.4}/></button></div>{children}</dialog>}
export function MediaView({media,className='',eager=false,sizes='(max-width:600px) 90vw, (max-width:1000px) 45vw, 35vw'}:{media:Media;className?:string;eager?:boolean;sizes?:string}){const {locale}=useStore();if(media.kind==='certificate')return <a className="text-link" href={media.src} download rel="noreferrer">{media.alt[locale]||t(locale,'included')}</a>;if(media.kind==='video')return <video className={className} controls preload="metadata" width={media.width} height={media.height}><source src={media.src} type={media.mime}/></video>;const local=media.src.startsWith('/media/')&&!media.src.includes('Logo');const remote=media.src.includes('/functions/v1/media-delivery?');const base=media.src.replace(/\.(jpeg|jpg)$/,'');return <picture>{local&&<source type="image/webp" srcSet={`${base}-320.webp 320w, ${base}-640.webp 640w, ${base}-1080.webp 1080w`} sizes={sizes}/>}<img className={className} src={media.src} srcSet={remote?[320,640,1080].map(w=>`${media.src}&w=${w} ${w}w`).join(', '):undefined} sizes={sizes} alt={media.alt[locale]} width={media.width} height={media.height} loading={eager?'eager':'lazy'} fetchPriority={eager?'high':'auto'} decoding="async"/></picture>}
export function Price({amount}:{amount:number}){const {locale}=useStore();return <bdi className="price">{formatMoney(amount,locale)}</bdi>}
/**
 * Latin model names (Polaris, Nova, Vega, Zenith, VVS1…) embedded in Arabic or
 * Hebrew copy are isolated explicitly instead of trusting bidi heuristics, and
 * are typeset in the Latin display face so they read as deliberate names.
 */
export function Isolate({text}:{text:string}){const {locale}=useStore();if(locale==='en'||!text)return <>{text}</>;return <>{splitLatinRuns(text).map((part,i)=>i%2?<bdi key={i} dir="ltr" className="latin">{part}</bdi>:<Fragment key={i}>{part}</Fragment>)}</>}
/** The four-point glint drawn from the THURAYA mark. */
export function Glint({className=''}:{className?:string}){return <svg className={`glint ${className}`.trim()} viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M12 0c.5 6.2 2.6 10.6 12 12-9.4 1.4-11.5 5.8-12 12-.5-6.2-2.6-10.6-12-12C9.4 10.6 11.5 6.2 12 0z" fill="currentColor"/></svg>}
export function ProductCard({product:p}:{product:Product}){const {locale,wishlist,toggleWish,data}=useStore();const prices=p.variants.filter(v=>v.active).map(v=>variantPrice(p,v));const minimum=prices.length?Math.min(...prices):p.basePrice;const saved=wishlist.includes(p.id);const category=data.categories.find(c=>c.id===p.categoryId);const href=`/${locale}/product/${p.slug}`;const {primary,alternate}=browseMedia(p.media);return <article className="product-card"><div className="card-media"><Link onClick={()=>analytics('select_item',{item_id:p.id})} to={href} tabIndex={-1} aria-hidden="true" className="card-image">{primary&&<MediaView media={primary} sizes="(max-width:600px) 50vw, (max-width:1000px) 50vw, 25vw"/>}{alternate?.kind==='image'&&<span className="card-alt"><MediaView media={alternate} sizes="(max-width:600px) 50vw, 25vw"/></span>}</Link><button className={`icon wish ${saved?'selected':''}`} aria-label={`${t(locale,'wishlist')}: ${p.name[locale]}`} aria-pressed={saved} onClick={()=>toggleWish(p.id)}><Heart size={17} strokeWidth={1.4} fill={saved?'currentColor':'none'}/></button>{p.isDemo&&<span className="badge">{t(locale,'demoProduct')}</span>}</div><div className="card-info">{category&&<span className="card-kicker">{category.name[locale]}</span>}<h3><Link onClick={()=>analytics('select_item',{item_id:p.id})} to={href}><Isolate text={p.name[locale]}/></Link></h3><span className="card-price">{minimum!==null&&<>{prices.length>0&&Math.max(...prices)>minimum&&<span className="from">{t(locale,'from')}</span>}<Price amount={minimum}/></>}</span></div></article>}
export function Empty({title,body}:{title?:string;body?:string}){const {locale}=useStore();return <div className="empty"><Glint/><h2>{title||t(locale,'empty')}</h2><p>{body||t(locale,'emptyBody')}</p><Link className="button" to={`/${locale}/shop`}>{t(locale,'explore')}<ArrowUpRight size={16} strokeWidth={1.5}/></Link></div>}
export function Field({label,error,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string;error?:string}){const id=props.name||label;return <label className="field" htmlFor={id}><span>{label}</span><input {...props} id={id} aria-invalid={!!error} aria-describedby={error?`${id}-error`:undefined}/>{error&&<span id={`${id}-error`} className="error">{error}</span>}</label>}
