import {useEffect,useRef,type ReactNode} from 'react';
import {Link} from 'react-router-dom';
import {X,Heart,ArrowUpRight} from 'lucide-react';
import type {Media,Product} from '../../shared/domain';
import {formatMoney,variantPrice} from '../../shared/logic';
import {useStore} from '../store';
import {t} from '../i18n';
export function Modal({open,onClose,title,children,drawer=false}:{open:boolean;onClose:()=>void;title:string;children:ReactNode;drawer?:boolean}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const d=ref.current;if(open&&!d?.open){d?.showModal();document.body.style.overflow='hidden'}else if(!open&&d?.open)d.close();return()=>{document.body.style.overflow=''}},[open]);return <dialog className={drawer?'drawer':'modal'} ref={ref} onCancel={onClose} onClose={onClose} onClick={e=>{if(e.target===ref.current)onClose()}} aria-label={title}><div className="dialog-head"><h2>{title}</h2><button className="icon" onClick={onClose} aria-label={t(useStore().locale,'close')}><X/></button></div>{children}</dialog>}
export function MediaView({media,className='',eager=false}:{media:Media;className?:string;eager?:boolean}){const {locale}=useStore();if(media.kind==='certificate')return <a className="text-link" href={media.src} download rel="noreferrer">{media.alt[locale]||t(locale,'included')}</a>;if(media.kind==='video')return <video className={className} controls preload="metadata" width={media.width} height={media.height}><source src={media.src} type={media.mime}/></video>;const local=media.src.startsWith('/media/')&&!media.src.includes('Logo');const remote=media.src.includes('/functions/v1/media-delivery?');const base=media.src.replace(/\.(jpeg|jpg)$/,'');return <picture>{local&&<source type="image/webp" srcSet={`${base}-320.webp 320w, ${base}-640.webp 640w, ${base}-1080.webp 1080w`} sizes="(max-width:600px) 90vw, (max-width:1000px) 45vw, 35vw"/>}<img className={className} src={media.src} srcSet={remote?[320,640,1080].map(w=>`${media.src}&w=${w} ${w}w`).join(', '):undefined} sizes="(max-width:600px) 90vw, (max-width:1000px) 45vw, 35vw" alt={media.alt[locale]} width={media.width} height={media.height} loading={eager?'eager':'lazy'} fetchPriority={eager?'high':'auto'}/></picture>}
export function Price({amount}:{amount:number}){const {locale}=useStore();return <bdi>{formatMoney(amount,locale)}</bdi>}
export function ProductCard({product:p}:{product:Product}){const {locale,wishlist,toggleWish}=useStore();const prices=p.variants.filter(v=>v.active).map(v=>variantPrice(p,v));const minimum=prices.length?Math.min(...prices):p.basePrice;return <article className="product-card"><div className="card-media"><Link onClick={()=>analytics('select_item',{item_id:p.id})} to={`/${locale}/product/${p.slug}`} tabIndex={-1} aria-hidden="true">{p.media[0]&&<MediaView media={p.media[0]}/>}</Link><button className={`icon wish ${wishlist.includes(p.id)?'selected':''}`} aria-label={`${t(locale,'wishlist')}: ${p.name[locale]}`} aria-pressed={wishlist.includes(p.id)} onClick={()=>toggleWish(p.id)}><Heart size={19} fill={wishlist.includes(p.id)?'currentColor':'none'}/></button>{p.isDemo&&<span className="badge">{t(locale,'demoProduct')}</span>}</div><div className="card-info"><h3><Link onClick={()=>analytics('select_item',{item_id:p.id})} to={`/${locale}/product/${p.slug}`}>{p.name[locale]}</Link></h3><span>{minimum!==null&&<>{Math.max(...prices)>minimum&&t(locale,'from')+' '}<Price amount={minimum}/></>}</span></div></article>}
export function Empty({title,body}:{title?:string;body?:string}){const {locale}=useStore();return <div className="empty"><span className="overline">THURAYA</span><h2>{title||t(locale,'empty')}</h2><p>{body||t(locale,'emptyBody')}</p><Link className="button" to={`/${locale}/shop`}>{t(locale,'explore')}<ArrowUpRight size={18}/></Link></div>}
export function Field({label,error,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string;error?:string}){const id=props.name||label;return <label className="field" htmlFor={id}><span>{label}</span><input {...props} id={id} aria-invalid={!!error} aria-describedby={error?`${id}-error`:undefined}/>{error&&<span id={`${id}-error`} className="error">{error}</span>}</label>}
import {analytics} from '../services/analytics';
