import {locales,type Product,type Variant,type CartLine,type Discount,type OrderStatus,type Role,type Order,type AdminOrder,type Localized,type Locale,type Notification} from './domain.ts';
export function integerMoney(n:number):number {if(!Number.isSafeInteger(n)||n<0)throw new Error('invalid_money');return n}
export function variantPrice(p:Product,v:Variant):number {if(p.basePrice===null)throw new Error('price_missing');integerMoney(p.basePrice);if(!Number.isSafeInteger(v.adjustment))throw new Error('invalid_adjustment');return integerMoney(p.basePrice+v.adjustment)}
export function uniqueCartLines(lines:readonly Pick<CartLine,'variantId'>[]){if(new Set(lines.map(line=>line.variantId)).size!==lines.length)throw new Error('duplicate_line')}
export function cartPrice(lines:CartLine[],products:Product[],shipping:number,discount?:Discount,now=Date.now()){integerMoney(shipping);if(!lines.length||lines.length>50)throw new Error('empty_cart');uniqueCartLines(lines);let eligible=0;let subtotal=0;for(const l of lines){if(!Number.isInteger(l.quantity)||l.quantity<1||l.quantity>10)throw new Error('invalid_quantity');const p=products.find(x=>x.id===l.productId&&x.status==='published'&&(!x.publishAt||Date.parse(x.publishAt)<=now));const v=p?.variants.find(x=>x.id===l.variantId&&x.active);if(!p||!v)throw new Error('unavailable');if(v.stock!==null&&v.stock<lines.filter(x=>x.variantId===v.id).reduce((s,x)=>s+x.quantity,0))throw new Error('stock');const amount=variantPrice(p,v)*l.quantity;subtotal+=amount;if(discount&&(!discount.productIds.length&&!discount.collectionIds.length||discount.productIds.includes(p.id)||p.collectionIds.some(x=>discount.collectionIds.includes(x))))eligible+=amount;}
 let saving=0;if(discount){validateDiscount(discount);if(!discount.active||discount.startsAt&&Date.parse(discount.startsAt)>now||discount.endsAt&&Date.parse(discount.endsAt)<=now||discount.usageLimit!==null&&discount.used>=discount.usageLimit||subtotal<discount.minimumSubtotal)throw new Error('discount_unavailable');saving=Math.min(eligible,discount.kind==='fixed'?discount.value:Math.floor(eligible*discount.value/100));if(!eligible)throw new Error('discount_unavailable');}return {subtotal,discount:saving,shipping,total:integerMoney(subtotal-saving+shipping)}}
export function validateDiscount(d:Discount){if(!Number.isSafeInteger(d.value)||d.value<=0||d.kind==='percentage'&&d.value>100||!Number.isSafeInteger(d.minimumSubtotal)||d.minimumSubtotal<0||!Number.isSafeInteger(d.used)||d.used<0||!d.code.trim()||[d.startsAt,d.endsAt].some(x=>x!==null&&!Number.isFinite(Date.parse(x)))||d.usageLimit!==null&&(!Number.isInteger(d.usageLimit)||d.usageLimit<1)||d.startsAt&&d.endsAt&&Date.parse(d.startsAt)>=Date.parse(d.endsAt))throw new Error('invalid_discount')}
const next:Record<OrderStatus,OrderStatus[]>={order_received:['payment_pending','cancelled'],payment_pending:['payment_confirmed','cancelled'],payment_confirmed:['in_production','refunded'],in_production:['quality_check','refunded'],quality_check:['ready_to_ship','in_production','refunded'],ready_to_ship:['shipped','quality_check','refunded'],shipped:['delivered','refunded'],delivered:['refunded'],cancelled:[],refunded:[]};
export const transitions=(s:OrderStatus)=>next[s];
export function assertTransition(from:OrderStatus,to:OrderStatus){if(!next[from].includes(to))throw new Error('invalid_transition')}
export function can(role:Role,area:string){if(role==='owner'||role==='admin')return true;if(role==='order_manager')return ['dashboard','orders','customers','inquiries','notifications','reviews'].includes(area);if(role==='content_manager')return ['dashboard','products','media','categories','collections','content','translations','reviews'].includes(area);return false}
export function publicationErrors(p:Product,override=false){const errors:string[]=[];if(!p.slug||!p.sku||!p.categoryId)errors.push('SKU, slug and category are required');if(p.basePrice===null||p.basePrice<0)errors.push('A confirmed price is required');if(!p.media.some(m=>m.kind==='image'))errors.push('A cover image is required');if(!p.variants.some(v=>v.active))errors.push('An active variant is required');if(!override)for(const l of locales)for(const k of ['name','shortDescription','description','seoTitle','seoDescription'] as const)if(!p[k][l].trim())errors.push(`${l.toUpperCase()}: ${k} missing`);for(const v of p.variants){try{variantPrice(p,v)}catch{errors.push(`Invalid price: ${v.sku}`)}for(const a of p.axes)if(!a.values.some(x=>x.id===v.options[a.id]))errors.push(`Variant ${v.sku}: ${a.id} missing`);}return [...new Set(errors)]}
export function publicOrder(o:AdminOrder):Order{return {id:o.id,number:o.number,customerId:o.customerId,locale:o.locale,status:o.status,paymentStatus:o.paymentStatus,paymentMethod:o.paymentMethod,items:o.items,subtotal:o.subtotal,discount:o.discount,shipping:o.shipping,total:o.total,createdAt:o.createdAt,etaMin:o.etaMin,etaMax:o.etaMax,events:o.events,safeTrackingUrl:o.safeTrackingUrl,isDemo:o.isDemo}}
export function normalizeContact(s:string){const t=s.trim().toLowerCase();if(t.includes('@'))return t;let n=t.replace(/[^\d+]/g,'');if(n.startsWith('05'))n='+972'+n.slice(1);if(n.startsWith('972'))n='+'+n;return n}
export async function contactHash(s:string,secret:string){if(secret.length<32)throw new Error('tracking_secret_missing');const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return Array.from(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(normalizeContact(s))))).map(n=>n.toString(16).padStart(2,'0')).join('')}
export function constantTimeEqual(a:string,b:string){let d=a.length^b.length;for(let i=0;i<Math.max(a.length,b.length);i++)d|=(a.charCodeAt(i)||0)^(b.charCodeAt(i)||0);return d===0}
export function localePath(path:string,locale:Locale){return /^\/(ar|he|en)(\/|$)/.test(path)?path.replace(/^\/(ar|he|en)/,`/${locale}`):`/${locale}`}
export function distance(a:string,b:string):number{const row=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let prev=row[0];row[0]=i;for(let j=1;j<=b.length;j++){const old=row[j];row[j]=Math.min(row[j]+1,row[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=old}}return row[b.length]}
export function searchMatch(p:Product,q:string){const hay=[...Object.values(p.name),...p.tags,p.sku].join(' ').toLocaleLowerCase();return q.trim().toLocaleLowerCase().split(/\s+/).every(w=>hay.includes(w)||w.length>3&&hay.split(/\s+/).some(x=>distance(x,w)<=1))}
export function deliveryRange(min:number,max:number,at=new Date()){if(!Number.isInteger(min)||max<min||min<0)throw new Error('invalid_delivery');return [new Date(at.getTime()+min*86400000),new Date(at.getTime()+max*86400000)]}
export const formatMoney=(cents:number,locale:Locale)=>new Intl.NumberFormat(locale==='ar'?'ar-IL':locale==='he'?'he-IL':'en-IL',{style:'currency',currency:'ILS',maximumFractionDigits:2}).format(cents/100);
export const parity=(x:Localized)=>locales.every(l=>typeof x[l]==='string'&&x[l].trim().length>0);
export function notificationKey(n:Pick<Notification,'eventId'|'channel'|'audience'>){return `${n.eventId}:${n.channel}:${n.audience}`}
export function canRetry(n:Notification){return n.status==='failed'&&n.attempts<5&&!n.uncertain&&(!n.firstAttemptAt||Date.parse(n.firstAttemptAt)>Date.now()-23*60*60*1000)}
export function mediaAllowed(mime:string,bytes:number,name:string){const ext=name.split('.').pop()?.toLowerCase();return bytes>0&&bytes<=20*1024*1024&&({'image/jpeg':['jpg','jpeg'],'image/png':['png'],'image/webp':['webp'],'image/avif':['avif'],'video/mp4':['mp4'],'application/pdf':['pdf']} as Record<string,string[]>)[mime]?.includes(ext||'')===true}
