import {localized as L,type ContentPage} from '../shared/domain';
// Editorial starting copy. Product claims remain exclusively in configured attributes.
export const educationPages:ContentPage[]=[
['moissanite',L('What is moissanite?','ما هو المويسانيت؟','מהו מויסנייט?'),L('Moissanite is a gemstone made of silicon carbide. It is a different material from diamond. Choosing between stones begins with understanding what each one is. Read the specifications of your chosen piece: stone type, dimensions and any grading or certification are shown only when confirmed for that product.','المويسانيت حجر يتكوّن من كربيد السيليكون، وهو مادة مختلفة عن الألماس. يبدأ اختيار الحجر بفهم طبيعته. راجع مواصفات القطعة التي تختارها: نوع الحجر وأبعاده ودرجاته أو شهادته لا تُعرض إلا عند تأكيدها لهذا المنتج.','מויסנייט הוא אבן העשויה מסיליקון קרביד. זהו חומר שונה מיהלום. הבחירה בין אבנים מתחילה בהבנת ההבדלים ביניהן. עיינו במפרט התכשיט שבחרתם: סוג האבן, מידותיה ודירוג או תעודה מוצגים רק כאשר אושרו עבור אותו מוצר.')],
['lab-grown-diamonds',L('Lab-grown diamonds','الألماس المزروع في المختبر','יהלומים שגודלו במעבדה'),L('Lab-grown diamonds are diamonds produced in a laboratory. They are distinct from diamond simulants such as moissanite. THURAYA is designed to welcome future lab-grown diamond collections. Availability and specifications are always stated on the individual product page.','الألماس المزروع في المختبر هو ألماس يُنتج في بيئة مختبرية، ويختلف عن الأحجار المشابهة للألماس مثل المويسانيت. يتيح متجر ثُرَيّا إضافة مجموعات من الألماس المزروع مستقبلًا. يُذكر التوفّر والمواصفات دائمًا في صفحة المنتج المعني.','יהלומים שגודלו במעבדה הם יהלומים המיוצרים במעבדה. הם שונים מחיקויי יהלום כגון מויסנייט. החנות של THURAYA ערוכה לקולקציות עתידיות של יהלומי מעבדה. זמינות ומפרט יצוינו תמיד בעמוד המוצר המסוים.')],
['jewelry-care',L('Caring for your piece','العناية بقطعتك','טיפול בתכשיט'),L('Care depends on the stone, metal, plating and setting. Follow the care information provided with your piece. Store jewelry separately to limit rubbing, and ask THURAYA before using chemical cleaners or ultrasonic equipment on an unfamiliar setting.','تختلف العناية بحسب الحجر والمعدن والطلاء والتثبيت. اتبع تعليمات العناية المرفقة بقطعتك. احفظ المجوهرات منفصلة لتقليل الاحتكاك، واستشر ثُرَيّا قبل استخدام المنظفات الكيميائية أو أجهزة التنظيف بالموجات فوق الصوتية على تثبيت غير مألوف.','הטיפול תלוי באבן, במתכת, בציפוי ובשיבוץ. פעלו לפי הוראות הטיפול של התכשיט. אחסנו תכשיטים בנפרד כדי להפחית חיכוך, ופנו ל-THURAYA לפני שימוש בחומרי ניקוי כימיים או בציוד אולטרסוני לשיבוץ שאינכם מכירים.')],
['ring-size',L('Finding your ring size','اختيار مقاس الخاتم','בחירת מידת טבעת'),L('A comfortable ring fits securely while passing over the knuckle. Fit can change during the day. Compare with a ring that fits the same finger, and contact our concierge to confirm the size system used by your chosen piece. Screen and paper measurements are estimates; do not assume a universal conversion.','يستقر الخاتم المريح بأمان مع إمكانية مروره فوق مفصل الإصبع. قد يتغيّر المقاس خلال اليوم. قارن بخاتم مناسب للإصبع نفسه وتواصل معنا لتأكيد نظام المقاسات الخاص بالقطعة. قياسات الشاشة والورق تقديرية؛ لا تفترض وجود تحويل موحّد.','טבעת נוחה יושבת בבטחה ועוברת מעל מפרק האצבע. ההתאמה עשויה להשתנות במהלך היום. השוו לטבעת המתאימה לאותה אצבע ופנו אלינו לאישור שיטת המידות של התכשיט. מדידות מסך ונייר הן הערכה בלבד; אין להניח שהמרה אחת מתאימה לכל שיטה.')],
['necklace-length',L('Choosing a necklace length','اختيار طول القلادة','בחירת אורך שרשרת'),L('Use a soft measuring tape or a cord to explore where you would like a necklace to sit. The same length rests differently on different people. Select a configured length on the product page, or request a custom length when available. A custom inquiry is confirmed and priced separately.','استخدم شريط قياس مرنًا أو خيطًا لتحديد موضع القلادة المرغوب. يظهر الطول نفسه بشكل مختلف من شخص لآخر. اختر طولًا متاحًا في صفحة المنتج أو اطلب طولًا خاصًا عند إتاحة ذلك. يُؤكّد الطلب الخاص ويُسعّر بصورة منفصلة.','השתמשו בסרט מדידה רך או בחוט כדי לבדוק היכן תרצו שהשרשרת תנוח. אותו אורך יושב אחרת על אנשים שונים. בחרו אורך זמין בעמוד המוצר, או בקשו אורך מותאם אם האפשרות קיימת. בקשה מותאמת דורשת אישור ותמחור נפרדים.')],
['bracelet-size',L('Choosing a bracelet fit','اختيار مقاس السوار','בחירת מידת צמיד'),L('Measure the wrist gently with a flexible tape and consider whether you prefer a closer or looser fit. Clasp and design affect comfort. Confirm the available lengths on the product page; our concierge can help with a custom-length request when the piece allows it.','قِس المعصم برفق بشريط مرن وحدّد ما إذا كنت تفضّل السوار قريبًا أو أوسع. يؤثر القفل والتصميم في الراحة. راجع الأطوال المتاحة في صفحة المنتج؛ يمكن لفريقنا مساعدتك بطلب طول خاص عندما تسمح القطعة بذلك.','מדדו את פרק כף היד בעדינות בסרט גמיש וחשבו אם אתם מעדיפים צמיד צמוד או רפוי יותר. הסוגר והעיצוב משפיעים על הנוחות. בדקו את האורכים הזמינים בעמוד המוצר; נשמח לסייע בבקשת אורך מותאם כאשר התכשיט מאפשר זאת.')]
].map(([slug,title,body])=>({id:String(slug),slug:String(slug),title:title as ContentPage['title'],body:body as ContentPage['body'],kind:'education',status:'published',legalReviewed:false}));
