import React from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter} from 'react-router-dom';
import {App} from './App';
import '@fontsource/cormorant-garamond/latin-400.css';
import '@fontsource/inter/latin-400.css';
import '@fontsource/noto-naskh-arabic/arabic-400.css';
import '@fontsource/noto-serif-hebrew/hebrew-400.css';
import './styles/main.css';
import './styles/storefront.css';
createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><App/></BrowserRouter></React.StrictMode>);
