import {educationPages} from './content';
import {newId} from '../shared/id';
import {localized as L,emptyLocalized,states,type AdminData,type Product,type Media,type Localized,type Settings,type Taxonomy} from '../shared/domain';
import {words,statusLabels} from './i18n';
const files=['01-Zenith-studs.jpeg','02-Copy-of-THURAYA-Instagram-post-BG-2.jpeg','03-Polaris-pendant.jpeg','04-Vega-2colors-1-.jpeg','06-Polaris-Necklace.jpeg','07-Nova.-Bracelets-1-.jpeg','08-Copy-of-THURAYA-Instagram-post-BG.jpeg'];
export const logoLight='/media/05-THURAYA_Logo2-2-1-.jpg';
export const logoDark='/media/09-THURAYA_Logo1-2-1-.jpg';
const names=[L('Zenith studs','أقراط Zenith','עגילי Zenith'),L('Pendant pair — name to confirm','تعليقتان — الاسم للتأكيد','זוג תליונים — שם לאישור'),L('Polaris artwork — halo studs','صورة Polaris — أقراط هالة','תמונת Polaris — עגילי הילה'),L('Vega rings','خواتم Vega','טבעות Vega'),L('Polaris necklace','قلادة Polaris','שרשרת Polaris'),L('Nova bracelet','سوار Nova','צמיד Nova'),L('Round studs — name to confirm','أقراط دائرية — الاسم للتأكيد','עגילים עגולים — שם לאישור')];
export const initialMedia:Media[]=files.map((f,i)=>({id:`asset-${i}`,src:`/media/${f}`,alt:names[i],kind:'image',width:1080,height:1350,position:i,mime:'image/jpeg'}));
/**
 * Approved THURAYA ecommerce product photography (pilot set, 2026-09).
 * Each piece ships as a pair in one 4:5 frame: a midnight frame for browsing
 * and a pearl frame for inspection. No text, no mark inside the image.
 * `shared/media-roles.ts` decides which frame each surface shows.
 */
const pilotAlt=(en:string,ar:string,he:string)=>L(en,ar,he);
const pilotPair=(slug:string,alt:{white:Localized;blue:Localized}):Media[]=>[
 {id:`${slug}-white`,src:`/media/${slug}-white.jpeg`,alt:alt.white,kind:'image',width:1122,height:1402,position:0,mime:'image/jpeg'},
 {id:`${slug}-blue`,src:`/media/${slug}-blue.jpeg`,alt:alt.blue,kind:'image',width:1122,height:1402,position:1,mime:'image/jpeg'},
];
export const pilotMedia:Record<string,Media[]>={
 'tennis-bracelet':pilotPair('tennis-bracelet',{white:pilotAlt('Tennis bracelet on a pearl background','سوار تنس على خلفية لؤلؤية','צמיד טניס על רקע פנינה'),blue:pilotAlt('Tennis bracelet on a midnight background','سوار تنس على خلفية ليلية','צמיד טניס על רקע כהה')}),
 'polaris-necklace':pilotPair('polaris-necklace',{white:pilotAlt('Polaris halo necklace on a pearl background','قلادة Polaris بهالة على خلفية لؤلؤية','שרשרת Polaris עם הילה על רקע פנינה'),blue:pilotAlt('Polaris halo necklace on a midnight background','قلادة Polaris بهالة على خلفية ليلية','שרשרת Polaris עם הילה על רקע כהה')}),
 'essential-studs':pilotPair('essential-studs',{white:pilotAlt('Solitaire studs on a pearl background','أقراط سوليتير على خلفية لؤلؤية','עגילי סוליטר על רקע פנינה'),blue:pilotAlt('Solitaire studs on a midnight background','أقراط سوليتير على خلفية ليلية','עגילי סוליטר על רקע כהה')}),
 'vega-rings':pilotPair('vega-rings',{white:pilotAlt('Pear solitaire rings on a pearl background','خاتما سوليتير بقطع الكمثرى على خلفية لؤلؤية','טבעות סוליטר בחיתוך אגס על רקע פנינה'),blue:pilotAlt('Pear solitaire rings on a midnight background','خاتما سوليتير بقطع الكمثرى على خلفية ليلية','טבעות סוליטר בחיתוך אגס על רקע כהה')}),
};
/** The approved midnight frame the homepage editorial band is built on — poster, print and fallback for the light loop. */
export const editorialStill:Media=pilotMedia['tennis-bracelet'][1];
/**
 * Every frame a CMS image reference can resolve against: the media library plus
 * the approved product frames. Sections store a path, not a media record, so the
 * storefront looks the record up here to keep intrinsic dimensions and localized
 * alt text intact. Presentation only — no schema, storage or validation change.
 */
export const siteMedia:Media[]=[...initialMedia,...Object.values(pilotMedia).flat()];
export function blankProduct():Product{return {id:newId(),sku:'',slug:'',status:'draft',name:emptyLocalized(),shortDescription:emptyLocalized(),description:emptyLocalized(),seoTitle:emptyLocalized(),seoDescription:emptyLocalized(),categoryId:'',collectionIds:[],tags:[],featured:false,bestseller:false,newArrival:false,publishAt:null,basePrice:null,compareAtPrice:null,gem:{},metal:{},measurements:{},axes:[],variants:[],media:[],madeToOrder:true,leadMin:null,leadMax:null,customization:false,shippingCountries:['IL'],included:emptyLocalized(),care:emptyLocalized(),isDemo:false,createdAt:new Date().toISOString()}}
const categoryNames=[L('Rings','خواتم','טבעות'),L('Necklaces','قلائد','שרשראות'),L('Pendants','تعليقات','תליונים'),L('Bracelets','أساور','צמידים'),L('Tennis bracelets','أساور تنس','צמידי טניס'),L('Earrings','أقراط','עגילים'),L('Studs','أقراط صغيرة','עגילים צמודים'),L('Sets','أطقم','סטים')];
export const categories:Taxonomy[]=categoryNames.map((name,i)=>({id:['rings','necklaces','pendants','bracelets','tennis','earrings','studs','sets'][i],slug:['rings','necklaces','pendants','bracelets','tennis','earrings','studs','sets'][i],name,description:emptyLocalized(),image:initialMedia[[3,4,1,5,5,0,6,2][i]].src,position:i,active:true}));
export const defaultSettings:Settings={currency:'ILS',siteUrl:'',contactEmail:'',whatsapp:'',instagram:'',leadMin:10,leadMax:14,internationalMode:'disabled',maintenance:false,checkoutEnabled:false,giftNote:false,freeShippingThreshold:null,emailEnabled:false,whatsappEnabled:false,requireMfa:true,announcement:words.announcement,story:words.storyBody,packaging:words.packagingBody,included:emptyLocalized(),paymentMethods:(['bank_transfer','paypal','card','bit','paybox'] as const).map(id=>({id,enabled:false,ready:false,test:true,instructions:emptyLocalized()})),templates:states.flatMap(status=>(['email','whatsapp'] as const).map(channel=>({id:`${status}-${channel}`,status,channel,enabled:true,subject:statusLabels[status],body:L(`Your THURAYA order: ${statusLabels[status].en}.`,`طلبك من ثُرَيّا: ${statusLabels[status].ar}.`,`הזמנת THURAYA שלך: ${statusLabels[status].he}.`),providerTemplate:emptyLocalized()}))),analytics:{ga4:'',meta:'',tiktok:''},statusLabels};
export function initialData(demo=false):AdminData{
 const products=initialMedia.map((m,i)=>({...blankProduct(),id:`draft-${i}`,sku:`TH-DRAFT-${i+1}`,slug:['zenith','pendants-unconfirmed','polaris-studs-unconfirmed','vega','polaris-necklace','nova','round-studs-unconfirmed'][i],name:names[i],categoryId:['studs','pendants','studs','rings','necklaces','bracelets','studs'][i],media:[m]}));
 if(demo)for(const i of [0,3,4,5]){const p=structuredClone(products[i]);const pilot=pilotMedia[({0:'essential-studs',3:'vega-rings',4:'polaris-necklace',5:'tennis-bracelet'} as Record<number,string>)[i]];if(pilot)p.media=structuredClone(pilot);const label=i===0?L('Essential studs','أقراط Essential','עגילי Essential'):names[i];p.id=`demo-${i}`;p.sku=`DEMO-${i}`;p.slug=`demo-${p.slug}`;p.name=L(`Demo · ${label.en}`,`تجريبي · ${label.ar}`,`הדגמה · ${label.he}`);p.status='published';p.basePrice=[38000,0,0,49000,64000,72000][i];p.isDemo=true;p.collectionIds=['celestial'];p.featured=true;p.newArrival=true;p.customization=true;p.shortDescription=L('A demonstration piece for exploring the THURAYA store.','قطعة تجريبية لاستكشاف متجر ثُرَيّا.','תכשיט לדוגמה להיכרות עם חנות THURAYA.');p.description=L('This is a local shopping demonstration using THURAYA reference artwork. Prices and options are test fixtures, not an offer for sale.','هذا عرض تسوّق تجريبي محلي باستخدام صور ثُرَيّا. الأسعار والخيارات للاختبار وليست عرضًا للبيع.','זוהי הדגמת קנייה מקומית עם תמונות THURAYA. המחירים והאפשרויות מיועדים לבדיקה ואינם הצעת מכר.');p.seoTitle=p.name;p.seoDescription=p.shortDescription;p.axes=[{id:'length',kind:i===3?'ring_size':i===4?'necklace_length':'bracelet_length',label:i===3?L('Ring size','مقاس الخاتم','מידת טבעת'):L('Length','الطول','אורך'),values:[{id:'standard',label:L('Standard · demo','قياسي · تجريبي','רגיל · הדגמה')},{id:'extended',label:L('Extended · demo','ممتد · تجريبي','מורחב · הדגמה')}]}];p.variants=p.axes[0].values.map((v,j)=>({id:`${p.id}-v${j}`,sku:`${p.sku}-${j}`,options:{length:v.id},adjustment:j*10000,active:true,stock:null,gem:{},metal:{},measurements:{},mediaIds:[]}));products.push(p);}
 const settings=structuredClone(defaultSettings);if(demo){settings.checkoutEnabled=true;settings.paymentMethods[0]={...settings.paymentMethods[0],enabled:true,ready:true,instructions:L('Local demonstration only. Do not transfer money.','عرض محلي فقط. لا تحوّل أي أموال.','הדגמה מקומית בלבד. אין להעביר כסף.')};}
 return {products,categories:structuredClone(categories),collections:[{id:'celestial',slug:'celestial',name:L('Celestial signatures','تواقيع سماوية','חתימות שמימיות'),description:words.heroBody,image:initialMedia[4].src,position:0,active:true}],sections:[
 {id:'hero',kind:'hero',enabled:true,position:0,title:words.hero,body:words.heroBody,cta:words.explore,href:'/shop',image:initialMedia[4].src,selection:[],layout:'split'},
 ...(['collections','standard','editorial','education','journey','story','packaging'] as const).map((kind,i)=>({id:kind,kind,enabled:true,position:i+1,title:words[({collections:'featured',standard:'standard',editorial:'editorialTitle',education:'education',journey:'journey',story:'storyTitle',packaging:'packaging'} as const)[kind]],body:kind==='story'?words.storyBody:kind==='journey'?words.journeyBody:kind==='packaging'?words.packagingBody:kind==='editorial'?words.editorialBody:words.standardBody,cta:words.discover,href:kind==='story'?'/about':kind==='education'?'/journal':'/shop',image:kind==='editorial'?editorialStill.src:initialMedia[3].src,selection:[],layout:'split' as const}))],settings,zones:demo?[{id:'israel-demo',name:L('Israel · demo delivery','إسرائيل · توصيل تجريبي','ישראל · משלוח לדוגמה'),country:'IL',cities:[],price:3500,etaMin:10,etaMax:14,active:true}]:[],pages:[...educationPages,...(['terms','privacy','shipping','returns','accessibility','cookies'] as const).map(slug=>({id:slug,slug,kind:'policy' as const,title:L(slug,slug,slug),body:emptyLocalized(),status:'draft' as const,legalReviewed:false}))],reviews:[],privateProducts:products.filter(p=>!p.isDemo).map(p=>({productId:p.id,supplierSku:'',supplierReference:'',cost:null,notes:'Confirm product identity, factual specifications, prices and translations before publication.'})),orders:[],customers:[],inquiries:[],discounts:[],notifications:[],audit:[],media:structuredClone(initialMedia)};
}
