begin;
create function private.l10n(p text,k text) returns jsonb language sql stable set search_path='' as $$select coalesce(jsonb_object_agg(locale,to_jsonb(t)->>k),'{}') from public.product_translations t where product_id=p$$;
create function private.product_view(p public.products) returns jsonb language sql stable set search_path='' as $$select jsonb_build_object('id',p.id,'sku',p.sku,'slug',p.slug,'status',p.status,'categoryId',p.category_id,'basePrice',p.base_price,'compareAtPrice',p.compare_at_price,'featured',p.featured,'bestseller',p.bestseller,'newArrival',p.new_arrival,'publishAt',p.publish_at,'madeToOrder',p.made_to_order,'leadMin',p.lead_min,'leadMax',p.lead_max,'customization',p.customization,'shippingCountries',p.shipping_countries,'tags',p.tags,'gem',p.gem,'metal',p.metal,'measurements',p.measurements,'isDemo',p.is_demo,'createdAt',p.created_at,'name',private.l10n(p.id,'name'),'shortDescription',private.l10n(p.id,'short_description'),'description',private.l10n(p.id,'description'),'seoTitle',private.l10n(p.id,'seo_title'),'seoDescription',private.l10n(p.id,'seo_description'),'included',private.l10n(p.id,'included'),'care',private.l10n(p.id,'care'),'collectionIds',(select coalesce(jsonb_agg(collection_id),'[]') from public.product_collections where product_id=p.id),'axes',(select coalesce(jsonb_agg(jsonb_build_object('id',a.id,'kind',a.kind,'label',a.label,'values',(select coalesce(jsonb_agg(jsonb_build_object('id',v.id,'label',v.label,'numericValue',v.numeric_value) order by position),'[]') from public.option_values v where axis_id=a.id)) order by a.position),'[]') from public.option_axes a where product_id=p.id),'variants',(select coalesce(jsonb_agg(jsonb_build_object('id',v.id,'sku',v.sku,'adjustment',v.adjustment,'active',v.active,'stock',v.stock,'gem',v.gem,'metal',v.metal,'measurements',v.measurements,'options',(select coalesce(jsonb_object_agg(axis_id,value_id),'{}') from public.variant_options where variant_id=v.id),'mediaIds',(select coalesce(jsonb_agg(media_id),'[]') from public.variant_media where variant_id=v.id))),'[]') from public.product_variants v where product_id=p.id),'media',(select coalesce(jsonb_agg(to_jsonb(m)||jsonb_build_object('storagePath',m.storage_path,'position',pm.position) order by pm.position),'[]') from public.product_media pm join public.media m on m.id=pm.media_id where pm.product_id=p.id))$$;
create function private.order_view(o public.orders) returns jsonb language sql stable set search_path='' as $$select jsonb_build_object('id',o.id,'number',o.number,'customerId',o.customer_id,'locale',o.locale,'status',o.status,'paymentStatus',o.payment_status,'paymentMethod',o.payment_method,'subtotal',o.subtotal,'discount',o.discount,'shipping',o.shipping,'total',o.total,'etaMin',o.eta_min,'etaMax',o.eta_max,'safeTrackingUrl',o.safe_tracking_url,'createdAt',o.created_at,'isDemo',false,'items',(select coalesce(jsonb_agg(jsonb_build_object('productId',i.product_id,'variantId',i.variant_id,'sku',i.sku,'name',i.name,'image',i.image,'options',i.options,'gem',i.gem,'metal',i.metal,'measurements',i.measurements,'quantity',i.quantity,'unitPrice',i.unit_price,'lineTotal',i.line_total)),'[]') from public.order_items i where order_id=o.id),'events',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'status',status,'at',at) order by at,id),'[]') from public.order_events where order_id=o.id))$$;
create function public.thuraya_snapshot(p_admin boolean default false,p_customer uuid default null) returns jsonb language plpgsql security definer set search_path='' as $$declare r jsonb;begin
select jsonb_build_object('products',(select coalesce(jsonb_agg(private.product_view(p) order by p.created_at desc),'[]') from public.products p where p_admin or (status='published' and (publish_at is null or publish_at<=now()))),'categories',(select coalesce(jsonb_agg(to_jsonb(c) order by position),'[]') from public.categories c where p_admin or active),'collections',(select coalesce(jsonb_agg(to_jsonb(c) order by position),'[]') from public.collections c where p_admin or active),'sections',(select coalesce(jsonb_agg(to_jsonb(s) order by position),'[]') from public.content_sections s where p_admin or enabled),'settings',(select config from public.store_settings limit 1),'zones',(select coalesce(jsonb_agg(to_jsonb(z)||jsonb_build_object('etaMin',eta_min,'etaMax',eta_max)),'[]') from public.shipping_zones z where p_admin or active),'pages',(select coalesce(jsonb_agg(to_jsonb(p)||jsonb_build_object('legalReviewed',legal_reviewed)),'[]') from public.content_pages p where p_admin or status='published' and (kind<>'policy' or legal_reviewed)),'reviews',(select coalesce(jsonb_agg(to_jsonb(r)||jsonb_build_object('productId',product_id,'customerId',customer_id,'createdAt',created_at)),'[]') from public.reviews r where p_admin or status='approved')) into r;
if p_admin then r=r||jsonb_build_object('orders',(select coalesce(jsonb_agg(private.order_view(o)||jsonb_build_object('customer',c.customer,'internalNotes',c.internal_notes,'supplierReference',c.supplier_reference) order by o.created_at desc),'[]') from public.orders o join private.order_contacts c on c.order_id=o.id),'privateProducts',(select coalesce(jsonb_agg(jsonb_build_object('productId',product_id,'supplierSku',supplier_sku,'supplierReference',supplier_reference,'cost',cost,'notes',notes)),'[]') from private.product_business),'customers',(select coalesce(jsonb_agg(to_jsonb(p)||jsonb_build_object('emailUpdates',email_updates,'whatsappUpdates',whatsapp_updates,'marketingConsent',marketing_consent)),'[]') from public.profiles p),'inquiries',(select coalesce(jsonb_agg(to_jsonb(i)||jsonb_build_object('productId',product_id,'createdAt',created_at)),'[]') from private.concierge_requests i),'discounts',(select coalesce(jsonb_agg(to_jsonb(d)||jsonb_build_object('startsAt',starts_at,'endsAt',ends_at,'usageLimit',usage_limit,'minimumSubtotal',minimum_subtotal,'productIds',product_ids,'collectionIds',collection_ids)),'[]') from private.discounts d),'notifications',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'eventId',event_id,'orderId',order_id,'channel',channel,'audience',audience,'templateId',template_id,'locale',locale,'status',status,'attempts',attempts,'providerId',provider_id,'sentAt',sent_at,'error',error,'nextAttemptAt',next_attempt_at)),'[]') from private.notification_outbox),'audit',(select coalesce(jsonb_agg(to_jsonb(a) order by at desc),'[]') from private.audit_log a),'media',(select coalesce(jsonb_agg(to_jsonb(m)||jsonb_build_object('storagePath',storage_path)),'[]') from public.media m));end if;return r;end$$;
create function private.enqueue(p_order text,p_event text,p_status text,p_owner boolean default false) returns void language plpgsql set search_path='' as $$declare s jsonb;loc text;ch text;t jsonb;consent boolean;begin select config into s from public.store_settings limit 1;select locale into loc from public.orders where id=p_order;select coalesce((customer->>'whatsappUpdates')::boolean,false) into consent from private.order_contacts where order_id=p_order;
foreach ch in array array['email','whatsapp'] loop select x into t from jsonb_array_elements(s->'templates') x where x->>'status'=p_status and x->>'channel'=ch limit 1;insert into private.notification_outbox(event_id,order_id,channel,audience,template_id,locale,status) values(p_event,p_order,ch,'customer',coalesce(t->>'id',p_status||'-'||ch),loc,case when coalesce((t->>'enabled')::boolean,false) and (ch='email' and coalesce((s->>'emailEnabled')::boolean,false) or ch='whatsapp' and consent and coalesce((s->>'whatsappEnabled')::boolean,false)) then 'pending' else 'disabled' end) on conflict do nothing;end loop;
if p_owner then insert into private.notification_outbox(event_id,order_id,channel,audience,template_id,locale,status) values(p_event,p_order,'email','owner','owner-new-order','en',case when coalesce((s->>'emailEnabled')::boolean,false) then 'pending' else 'disabled' end) on conflict do nothing;end if;end$$;
create function public.thuraya_place_order(p_input jsonb,p_email_hash text,p_phone_hash text,p_request_hash text,p_customer uuid default null) returns jsonb language plpgsql security definer set search_path='' as $$declare existing private.checkout_keys;cfg jsonb;z public.shipping_zones;d private.discounts;l jsonb;p public.products;v public.product_variants;sub integer:=0;eligible integer:=0;saving integer:=0;ship integer;qty integer;unit integer;ord public.orders;ev text;idkey uuid:=(p_input->>'idempotencyKey')::uuid;emin integer;emax integer;method jsonb;begin
perform pg_advisory_xact_lock(hashtextextended(idkey::text,0));select * into existing from private.checkout_keys where key=idkey;if found then if existing.request_hash<>p_request_hash then raise exception 'idempotency_conflict';end if;select * into ord from public.orders where id=existing.order_id;return private.order_view(ord);end if;
select config into cfg from public.store_settings limit 1;if not coalesce((cfg->>'checkoutEnabled')::boolean,false) or coalesce((cfg->>'maintenance')::boolean,false) then raise exception 'checkout_unavailable';end if;
select x into method from jsonb_array_elements(cfg->'paymentMethods') x where x->>'id'=p_input->>'paymentMethod';if not coalesce((method->>'enabled')::boolean,false) then raise exception 'payment_unavailable';end if;
select * into z from public.shipping_zones where id=p_input->>'zoneId' and active and country=p_input->>'country';if not found or cardinality(z.cities)>0 and not (p_input->>'city'=any(z.cities)) then raise exception 'shipping_unavailable';end if;
if coalesce(p_input->>'discountCode','')<>'' then select * into d from private.discounts where upper(code)=upper(p_input->>'discountCode') for update;if not found or not d.active or d.starts_at>now() or d.ends_at<=now() or d.usage_limit is not null and d.used>=d.usage_limit then raise exception 'discount_unavailable';end if;end if;
emin:=greatest(z.eta_min,(cfg->>'leadMin')::integer);emax:=greatest(z.eta_max,(cfg->>'leadMax')::integer);
-- Lock variants in stable order; inventory and coupon usage are serialized.
perform 1 from public.product_variants where id in(select x->>'variantId' from jsonb_array_elements(p_input->'lines') x) order by id for update;
for l in select x from jsonb_array_elements(p_input->'lines') x loop qty:=(l->>'quantity')::integer;if qty<1 or qty>10 then raise exception 'invalid_quantity';end if;select * into p from public.products where id=l->>'productId' and status='published' and (publish_at is null or publish_at<=now()) for share;if not found or p.base_price is null or not ((p_input->>'country')=any(p.shipping_countries)) then raise exception 'unavailable';end if;select * into v from public.product_variants where id=l->>'variantId' and product_id=p.id and active;if not found then raise exception 'unavailable';end if;unit:=p.base_price+v.adjustment;if unit<0 then raise exception 'invalid_price';end if;if v.stock is not null then update public.product_variants set stock=stock-qty where id=v.id and stock>=qty;if not found then raise exception 'stock';end if;end if;sub:=sub+unit*qty;if d.id is not null and (cardinality(d.product_ids)=0 and cardinality(d.collection_ids)=0 or p.id=any(d.product_ids) or exists(select 1 from public.product_collections where product_id=p.id and collection_id=any(d.collection_ids))) then eligible:=eligible+unit*qty;end if;emin:=greatest(emin,coalesce(p.lead_min,(cfg->>'leadMin')::integer));emax:=greatest(emax,coalesce(p.lead_max,(cfg->>'leadMax')::integer));end loop;
if sub<=0 then raise exception 'invalid_total';end if;if d.id is not null then if sub<d.minimum_subtotal or eligible=0 then raise exception 'discount_unavailable';end if;saving:=least(eligible,case when d.kind='fixed' then d.value else floor(eligible::numeric*d.value/100)::integer end);end if;
ship:=case when cfg->>'freeShippingThreshold' is not null and sub>=(cfg->>'freeShippingThreshold')::integer then 0 else z.price end;
insert into public.orders(customer_id,locale,payment_method,subtotal,discount,shipping,total,eta_min,eta_max) values(p_customer,p_input->>'locale',p_input->>'paymentMethod',sub,saving,ship,sub-saving+ship,emin,emax) returning * into ord;
insert into private.order_contacts(order_id,email_hash,phone_hash,customer) values(ord.id,p_email_hash,p_phone_hash,p_input-'lines'-'idempotencyKey'-'turnstileToken');
for l in select x from jsonb_array_elements(p_input->'lines') x loop select * into p from public.products where id=l->>'productId';select * into v from public.product_variants where id=l->>'variantId';unit:=p.base_price+v.adjustment;qty:=(l->>'quantity')::integer;insert into public.order_items(order_id,product_id,variant_id,sku,name,image,options,gem,metal,measurements,quantity,unit_price,line_total) values(ord.id,p.id,v.id,v.sku,private.l10n(p.id,'name'),coalesce((select src from public.product_media pm join public.media m on m.id=pm.media_id where pm.product_id=p.id order by pm.position limit 1),''),(select coalesce(jsonb_agg(ov.label),'[]') from public.variant_options vo join public.option_values ov on ov.id=vo.value_id where vo.variant_id=v.id),p.gem||v.gem,p.metal||v.metal,p.measurements||v.measurements,qty,unit,unit*qty);end loop;
insert into public.order_events(order_id,status) values(ord.id,'order_received') returning id into ev;perform private.enqueue(ord.id,ev,'order_received',true);insert into public.order_events(order_id,status,at) values(ord.id,'payment_pending',now()+interval '1 millisecond');
insert into private.checkout_keys(key,request_hash,order_id) values(idkey,p_request_hash,ord.id);if d.id is not null then update private.discounts set used=used+1 where id=d.id;insert into private.discount_redemptions(discount_id,order_id,amount) values(d.id,ord.id,saving);end if;insert into private.audit_log(actor,action,target,summary) values(coalesce(p_customer::text,'guest'),'order_created',ord.id,'Order and notification outbox committed');return private.order_view(ord);end$$;
create function public.thuraya_change_order(p_id text,p_status text,p_actor text,p_provider boolean default false) returns jsonb language plpgsql security definer set search_path='' as $$declare o public.orders;allowed text[];ev text;begin select * into o from public.orders where id=p_id for update;if not found then raise exception 'not_found';end if;
allowed:=case o.status when 'order_received' then array['payment_pending','cancelled'] when 'payment_pending' then array['payment_confirmed','cancelled'] when 'payment_confirmed' then array['in_production','refunded'] when 'in_production' then array['quality_check','refunded'] when 'quality_check' then array['ready_to_ship','in_production','refunded'] when 'ready_to_ship' then array['shipped','quality_check','refunded'] when 'shipped' then array['delivered','refunded'] when 'delivered' then array['refunded'] else array[]::text[] end;
if not (p_status=any(allowed)) then raise exception 'invalid_transition';end if;if p_status in('payment_confirmed','refunded') and o.payment_method<>'bank_transfer' and not p_provider then raise exception 'provider_confirmation_required';end if;
update public.orders set status=p_status,payment_status=case when p_status='payment_confirmed' then 'paid' when p_status='refunded' then 'refunded' else payment_status end where id=p_id returning * into o;insert into public.order_events(order_id,status) values(p_id,p_status) returning id into ev;perform private.enqueue(p_id,ev,p_status);insert into private.audit_log(actor,action,target,summary) values(p_actor,'order_status',p_id,p_status);return private.order_view(o);end$$;
create function public.thuraya_track(p_number text,p_contact_hash text) returns jsonb language sql security definer set search_path='' as $$select private.order_view(o) from public.orders o join private.order_contacts c on c.order_id=o.id where o.number=p_number and (c.email_hash=p_contact_hash or c.phone_hash=p_contact_hash)$$;
create function public.thuraya_customer_orders(p_customer uuid) returns jsonb language sql security definer set search_path='' as $$select coalesce(jsonb_agg(private.order_view(o) order by created_at desc),'[]') from public.orders o where customer_id=p_customer$$;
create function public.thuraya_rate_limit(p_key text,p_limit integer,p_seconds integer) returns boolean language plpgsql security definer set search_path='' as $$declare n integer;begin insert into private.rate_limits(key) values(p_key) on conflict(key) do update set hits=case when private.rate_limits.window_start<now()-make_interval(secs=>p_seconds) then 1 else private.rate_limits.hits+1 end,window_start=case when private.rate_limits.window_start<now()-make_interval(secs=>p_seconds) then now() else private.rate_limits.window_start end returning hits into n;return n<=p_limit;end$$;
revoke execute on all functions in schema public from public,anon,authenticated;
grant execute on all functions in schema public to service_role;
revoke execute on all functions in schema private from public,anon,authenticated;
commit;
