begin;
create function private.upsert_row(p_schema text,p_table text,p_value jsonb,p_key text default 'id') returns void language plpgsql set search_path='' as $$declare cols text;updates text;begin
select string_agg(format('%I',key),','),string_agg(format('%I=excluded.%I',key,key),',') into cols,updates from jsonb_object_keys(p_value) key where key<>p_key;
execute format('insert into %I.%I (%I,%s) select %I,%s from jsonb_populate_record(null::%I.%I,$1) on conflict(%I) do update set %s',p_schema,p_table,p_key,cols,p_key,cols,p_schema,p_table,p_key,updates) using p_value;end$$;
create function public.thuraya_save_product(p jsonb,p_actor uuid,p_override boolean default false) returns void language plpgsql security definer set search_path='' as $$declare a jsonb;v jsonb;m jsonb;lang text;role text;pid text:=p->>'id';row jsonb;pos integer;opt record;begin select profiles.role into role from public.profiles where id=p_actor;if role not in('owner','admin','content_manager') then raise exception 'forbidden';end if;if coalesce((p->>'isDemo')::boolean,false) then raise exception 'demo_forbidden';end if;
if p->>'status'='published' then if p->>'basePrice' is null or jsonb_array_length(p->'variants')=0 or jsonb_array_length(p->'media')=0 then raise exception 'publication_incomplete';end if;if not(p_override and role='owner') then foreach lang in array array['ar','he','en'] loop if length(trim(coalesce(p->'name'->>lang,'')))=0 or length(trim(coalesce(p->'shortDescription'->>lang,'')))=0 or length(trim(coalesce(p->'description'->>lang,'')))=0 or length(trim(coalesce(p->'seoTitle'->>lang,'')))=0 or length(trim(coalesce(p->'seoDescription'->>lang,'')))=0 then raise exception 'translation_incomplete';end if;end loop;end if;end if;
row:=jsonb_build_object('id',pid,'sku',p->>'sku','slug',p->>'slug','status',p->>'status','category_id',nullif(p->>'categoryId',''),'base_price',p->'basePrice','compare_at_price',p->'compareAtPrice','featured',p->'featured','bestseller',p->'bestseller','new_arrival',p->'newArrival','publish_at',p->'publishAt','made_to_order',p->'madeToOrder','lead_min',p->'leadMin','lead_max',p->'leadMax','customization',p->'customization','shipping_countries',p->'shippingCountries','tags',p->'tags','gem',p->'gem','metal',p->'metal','measurements',p->'measurements','updated_at',now());perform private.upsert_row('public','products',row);
foreach lang in array array['ar','he','en'] loop insert into public.product_translations(product_id,locale,name,short_description,description,seo_title,seo_description,included,care) values(pid,lang,coalesce(p->'name'->>lang,''),coalesce(p->'shortDescription'->>lang,''),coalesce(p->'description'->>lang,''),coalesce(p->'seoTitle'->>lang,''),coalesce(p->'seoDescription'->>lang,''),coalesce(p->'included'->>lang,''),coalesce(p->'care'->>lang,'')) on conflict(product_id,locale) do update set name=excluded.name,short_description=excluded.short_description,description=excluded.description,seo_title=excluded.seo_title,seo_description=excluded.seo_description,included=excluded.included,care=excluded.care;end loop;
delete from public.product_collections where product_id=pid;insert into public.product_collections select pid,value from jsonb_array_elements_text(p->'collectionIds');
-- Keep referenced variants permanently. Removed variants become inactive.
update public.product_variants set active=false where product_id=pid;
for a in select x from jsonb_array_elements(p->'axes') x loop perform private.upsert_row('public','option_axes',jsonb_build_object('id',a->>'id','product_id',pid,'kind',a->>'kind','label',a->'label'));for v in select x from jsonb_array_elements(a->'values') x loop perform private.upsert_row('public','option_values',jsonb_build_object('id',v->>'id','axis_id',a->>'id','label',v->'label','numeric_value',v->'numericValue'));end loop;end loop;
for v in select x from jsonb_array_elements(p->'variants') x loop if (p->>'basePrice')::integer+(v->>'adjustment')::integer<0 then raise exception 'invalid_price';end if;perform private.upsert_row('public','product_variants',jsonb_build_object('id',v->>'id','product_id',pid,'sku',v->>'sku','adjustment',v->'adjustment','active',v->'active','stock',v->'stock','gem',v->'gem','metal',v->'metal','measurements',v->'measurements'));delete from public.variant_options where variant_id=v->>'id';for opt in select * from jsonb_each_text(v->'options') loop if not exists(select 1 from public.option_values ov join public.option_axes ax on ax.id=ov.axis_id where ov.id=opt.value and ax.id=opt.key and ax.product_id=pid) then raise exception 'invalid_variant_option';end if;insert into public.variant_options values(v->>'id',opt.key,opt.value);end loop;end loop;
delete from public.product_media where product_id=pid;pos:=0;for m in select x from jsonb_array_elements(p->'media') x loop perform private.upsert_row('public','media',jsonb_build_object('id',m->>'id','src',m->>'src','storage_path',m->'storagePath','alt',m->'alt','kind',m->>'kind','width',m->'width','height',m->'height','mime',m->>'mime','bytes',m->'bytes','position',pos));insert into public.product_media values(pid,m->>'id',pos);pos:=pos+1;end loop;
for v in select x from jsonb_array_elements(p->'variants') x loop delete from public.variant_media where variant_id=v->>'id';insert into public.variant_media select v->>'id',value from jsonb_array_elements_text(v->'mediaIds');end loop;
insert into private.audit_log(actor,action,target,summary) values(p_actor::text,'product_saved',pid,case when p_override then 'Owner translation override' else p->>'status' end);end$$;
create function public.thuraya_admin_write(p_entity text,p_value jsonb,p_actor uuid) returns void language plpgsql security definer set search_path='' as $$declare schema_name text:='public';tbl text;role text;oldrow jsonb;begin select profiles.role into role from public.profiles where id=p_actor;if role not in('owner','admin','content_manager','order_manager') then raise exception 'forbidden';end if;
if role='content_manager' and p_entity not in('categories','collections','sections','pages','media','reviews') or role='order_manager' and p_entity not in('inquiries','reviews') then raise exception 'forbidden';end if;
case p_entity when 'categories' then tbl:='categories';when 'collections' then tbl:='collections';when 'sections' then tbl:='content_sections';when 'pages' then tbl:='content_pages';when 'zones' then tbl:='shipping_zones';when 'media' then tbl:='media';when 'reviews' then tbl:='reviews';when 'inquiries' then schema_name:='private';tbl:='concierge_requests';when 'discounts' then schema_name:='private';tbl:='discounts';else raise exception 'invalid_entity';end case;
if p_entity='reviews' then update public.reviews set status=p_value->>'status' where id=p_value->>'id';elsif p_entity='inquiries' then update private.concierge_requests set status=p_value->>'status' where id=p_value->>'id';else if p_entity='discounts' then p_value:=p_value-'used';end if;perform private.upsert_row(schema_name,tbl,p_value);end if;
insert into private.audit_log(actor,action,target,summary) values(p_actor::text,'save_'||p_entity,p_value->>'id','Record updated');end$$;
create function public.thuraya_save_settings(p_settings jsonb,p_actor uuid) returns void language plpgsql security definer set search_path='' as $$declare role text;begin select profiles.role into role from public.profiles where id=p_actor;if role not in('owner','admin') then raise exception 'forbidden';end if;if (p_settings->>'leadMin')::integer<0 or (p_settings->>'leadMax')::integer<(p_settings->>'leadMin')::integer then raise exception 'invalid_delivery';end if;insert into public.store_settings values(true,p_settings) on conflict(id) do update set config=excluded.config;insert into private.audit_log(actor,action,target,summary) values(p_actor::text,'settings_saved','store','Configuration updated');end$$;
create function public.thuraya_private_write(p_action text,p_value jsonb,p_actor uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare role text;begin select profiles.role into role from public.profiles where id=p_actor;
if p_action='product' then if role not in('owner','admin') then raise exception 'forbidden';end if;perform private.upsert_row('private','product_business',p_value,'product_id');
elsif p_action='order' then if role not in('owner','admin','order_manager') then raise exception 'forbidden';end if;update private.order_contacts set internal_notes=p_value->>'internalNotes',supplier_reference=p_value->>'supplierReference' where order_id=p_value->>'id';update public.orders set safe_tracking_url=nullif(p_value->>'safeTrackingUrl',''),eta_min=(p_value->>'etaMin')::integer,eta_max=(p_value->>'etaMax')::integer where id=p_value->>'id';
elsif p_action='retry' then if role not in('owner','admin','order_manager') then raise exception 'forbidden';end if;update private.notification_outbox set status='pending',next_attempt_at=now(),locked_at=null where id=p_value->>'id' and status='failed' and attempts<5 and not uncertain and (first_attempt_at is null or first_attempt_at>now()-interval '23 hours');if not found then raise exception 'not_retryable';end if;
elsif p_action='inquiry' then insert into private.concierge_requests(product_id,name,email,phone,message,locale) values(nullif(p_value->>'productId',''),p_value->>'name',p_value->>'email',p_value->>'phone',p_value->>'message',p_value->>'locale');
elsif p_action='upload-ticket' then if role not in('owner','admin','content_manager') then raise exception 'forbidden';end if;insert into private.upload_tickets(path,actor,mime,bytes) values(p_value->>'path',p_actor,p_value->>'mime',(p_value->>'bytes')::integer);
elsif p_action='upload-check' then if role not in('owner','admin','content_manager') then raise exception 'forbidden';end if;return (select to_jsonb(t) from private.upload_tickets t where path=p_value->>'path' and actor=p_actor);
elsif p_action='upload-confirm' then update private.upload_tickets set confirmed=true where path=p_value->>'path' and actor=p_actor;
elsif p_action='delete-media' then if role not in('owner','admin','content_manager') then raise exception 'forbidden';end if;delete from public.media where id=p_value->>'id';
else raise exception 'invalid_action';end if;insert into private.audit_log(actor,action,target,summary) values(coalesce(p_actor::text,'guest'),p_action,coalesce(p_value->>'id',p_value->>'path',p_value->>'product_id','request'),'Operation recorded');return '{}'::jsonb;end$$;
create function public.thuraya_payment_event(p_provider text,p_event text,p_order text,p_amount integer,p_currency text,p_outcome text) returns jsonb language plpgsql security definer set search_path='' as $$declare o public.orders;begin select * into o from public.orders where id=p_order for update;if not found or p_currency<>'ILS' or o.total<>p_amount then raise exception 'payment_mismatch';end if;insert into private.payment_events values(p_provider,p_event,p_order,p_amount,p_currency,p_outcome,now()) on conflict do nothing;if not found then return jsonb_build_object('duplicate',true);end if;if p_outcome='paid' and o.payment_status<>'paid' then perform public.thuraya_change_order(p_order,'payment_confirmed','provider:'||p_provider,true);end if;return jsonb_build_object('ok',true);end$$;
create function public.thuraya_claim_notifications() returns jsonb language plpgsql security definer set search_path='' as $$declare result jsonb;begin
-- An abandoned WhatsApp claim is ambiguous: hold for reconciliation, never resend.
update private.notification_outbox set status='failed',uncertain=true,error='Unknown provider outcome; reconcile before any new send' where channel='whatsapp' and locked_at<now()-interval '5 minutes' and status='pending';
with claimed as (select id from private.notification_outbox where status='pending' and not uncertain and attempts<5 and (next_attempt_at is null or next_attempt_at<=now()) and (locked_at is null or channel='email' and locked_at<now()-interval '5 minutes' and first_attempt_at>now()-interval '23 hours') order by id for update skip locked limit 20),updated as(update private.notification_outbox n set locked_at=now(),first_attempt_at=coalesce(first_attempt_at,now()),attempts=attempts+1 from claimed where n.id=claimed.id returning n.*) select coalesce(jsonb_agg(to_jsonb(u)||jsonb_build_object('order',private.order_view(o),'contact',c.customer)),'[]') into result from updated u join public.orders o on o.id=u.order_id join private.order_contacts c on c.order_id=o.id;return result;end$$;
create function public.thuraya_notification_result(p_id text,p_status text,p_provider_id text,p_error text,p_uncertain boolean default false,p_payload jsonb default null) returns void language plpgsql security definer set search_path='' as $$declare n private.notification_outbox;begin update private.notification_outbox set status=p_status,provider_id=p_provider_id,error=left(p_error,300),uncertain=p_uncertain,sent_at=case when p_status='sent' then now() else sent_at end,next_attempt_at=case when p_status='failed' and not p_uncertain then now()+interval '5 minutes' end,locked_at=null,payload=coalesce(payload,p_payload) where id=p_id returning * into n;insert into private.notification_logs(notification_id,attempt,outcome,provider_id,error) values(p_id,n.attempts,p_status,p_provider_id,left(p_error,300));end$$;
revoke execute on all functions in schema public from public,anon,authenticated;
grant execute on all functions in schema public to service_role;
revoke execute on all functions in schema private from public,anon,authenticated;
commit;
