begin;
-- Avoid collision between a PL/pgSQL result variable and the review row alias.
create or replace function public.thuraya_snapshot(p_admin boolean default false,p_customer uuid default null) returns jsonb language plpgsql security definer set search_path='' as $$declare snapshot_result jsonb;begin
select jsonb_build_object('products',(select coalesce(jsonb_agg(private.product_view(p) order by p.created_at desc),'[]') from public.products p where p_admin or (status='published' and (publish_at is null or publish_at<=now()))),'categories',(select coalesce(jsonb_agg(to_jsonb(c) order by position),'[]') from public.categories c where p_admin or active),'collections',(select coalesce(jsonb_agg(to_jsonb(c) order by position),'[]') from public.collections c where p_admin or active),'sections',(select coalesce(jsonb_agg(to_jsonb(s) order by position),'[]') from public.content_sections s where p_admin or enabled),'settings',(select config from public.store_settings limit 1),'zones',(select coalesce(jsonb_agg(to_jsonb(z)||jsonb_build_object('etaMin',eta_min,'etaMax',eta_max)),'[]') from public.shipping_zones z where p_admin or active),'pages',(select coalesce(jsonb_agg(to_jsonb(p)||jsonb_build_object('legalReviewed',legal_reviewed)),'[]') from public.content_pages p where p_admin or status='published' and (kind<>'policy' or legal_reviewed)),'reviews',(select coalesce(jsonb_agg(to_jsonb(r)||jsonb_build_object('productId',product_id,'customerId',customer_id,'createdAt',created_at)),'[]') from public.reviews r where p_admin or status='approved')) into snapshot_result;
if p_admin then snapshot_result=snapshot_result||jsonb_build_object('orders',(select coalesce(jsonb_agg(private.order_view(o)||jsonb_build_object('customer',c.customer,'internalNotes',c.internal_notes,'supplierReference',c.supplier_reference) order by o.created_at desc),'[]') from public.orders o join private.order_contacts c on c.order_id=o.id),'privateProducts',(select coalesce(jsonb_agg(jsonb_build_object('productId',product_id,'supplierSku',supplier_sku,'supplierReference',supplier_reference,'cost',cost,'notes',notes)),'[]') from private.product_business),'customers',(select coalesce(jsonb_agg(to_jsonb(p)||jsonb_build_object('emailUpdates',email_updates,'whatsappUpdates',whatsapp_updates,'marketingConsent',marketing_consent)),'[]') from public.profiles p),'inquiries',(select coalesce(jsonb_agg(to_jsonb(i)||jsonb_build_object('productId',product_id,'createdAt',created_at)),'[]') from private.concierge_requests i),'discounts',(select coalesce(jsonb_agg(to_jsonb(d)||jsonb_build_object('startsAt',starts_at,'endsAt',ends_at,'usageLimit',usage_limit,'minimumSubtotal',minimum_subtotal,'productIds',product_ids,'collectionIds',collection_ids)),'[]') from private.discounts d),'notifications',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'eventId',event_id,'orderId',order_id,'channel',channel,'audience',audience,'templateId',template_id,'locale',locale,'status',status,'attempts',attempts,'providerId',provider_id,'sentAt',sent_at,'error',error,'nextAttemptAt',next_attempt_at)),'[]') from private.notification_outbox),'audit',(select coalesce(jsonb_agg(to_jsonb(a) order by at desc),'[]') from private.audit_log a),'media',(select coalesce(jsonb_agg(to_jsonb(m)||jsonb_build_object('storagePath',storage_path)),'[]') from public.media m));end if;return snapshot_result;end$$;

revoke all on function public.thuraya_snapshot(boolean,uuid) from public,anon,authenticated;
grant execute on function public.thuraya_snapshot(boolean,uuid) to service_role;
commit;
