import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {initialData} from '../../src/seed.ts';
import {cartPrice,variantPrice,publicationErrors,assertTransition,transitions,can,contactHash,constantTimeEqual,normalizeContact,localePath,searchMatch,deliveryRange,parity,notificationKey,mediaAllowed,validateDiscount,publicOrder,formatMoney,formatNumber,formatDate} from '../../shared/logic.ts';
import {checkoutSchema} from '../../shared/validation.ts';
import {words} from '../../src/i18n.ts';
import {escapeHtml} from '../../shared/notifications.ts';
import type {Discount,AdminOrder} from '../../shared/domain.ts';
const p=initialData(true).products.find(p=>p.isDemo)!;const lines=[{productId:p.id,variantId:p.variants[0].id,quantity:2}];const coupon:Discount={id:'x',code:'TEST',kind:'percentage',value:10,active:true,startsAt:null,endsAt:null,usageLimit:1,used:0,minimumSubtotal:0,productIds:[],collectionIds:[]};
test('variant adjustment updates integer minor units',()=>assert.equal(variantPrice(p,p.variants[1]),p.basePrice!+10000));
test('server recomputation ignores any client total',()=>assert.equal(cartPrice(lines,[p],3500).total,p.basePrice!*2+3500));
test('percentage discount excludes shipping',()=>assert.equal(cartPrice(lines,[p],3500,coupon).discount,7600));
test('fixed discount cannot make total negative',()=>assert.equal(cartPrice(lines,[p],0,{...coupon,kind:'fixed',value:999999}).total,0));
test('discount product eligibility',()=>assert.throws(()=>cartPrice(lines,[p],0,{...coupon,productIds:['other']})));
test('expired discount rejected',()=>assert.throws(()=>cartPrice(lines,[p],0,{...coupon,endsAt:'2000-01-01T00:00:00Z'})));
test('exhausted coupon rejected',()=>assert.throws(()=>cartPrice(lines,[p],0,{...coupon,used:1})));
test('invalid percentage rejected',()=>assert.throws(()=>validateDiscount({...coupon,value:101})));
test('aggregate duplicate stock checked',()=>{const x=structuredClone(p);x.variants[0].stock=3;assert.throws(()=>cartPrice([...lines,...lines],[x],0))});
test('duplicate cart variants are rejected before pricing or order submission',()=>assert.throws(()=>cartPrice([...lines,...lines],[p],0),/duplicate_line/));
test('negative variant price rejected',()=>assert.throws(()=>variantPrice(p,{...p.variants[0],adjustment:-999999})));
test('fractional quantity rejected',()=>assert.throws(()=>cartPrice([{...lines[0],quantity:1.5}],[p],0)));
test('draft purchase rejected',()=>assert.throws(()=>cartPrice(lines,[{...p,status:'draft'}],0)));
test('future publication cannot be purchased',()=>assert.throws(()=>cartPrice(lines,[{...p,publishAt:'2099-01-01T00:00:00Z'}],0)));
test('real draft products have no invented prices or specifications',()=>{for(const p of initialData().products){assert.equal(p.status,'draft');assert.equal(p.basePrice,null);assert.deepEqual(p.gem,{})}});
test('production seed contains no demo products/reviews',()=>{assert.ok(initialData().products.every(p=>!p.isDemo));assert.equal(initialData().reviews.length,0)});
test('publication requires Hebrew',()=>{const x=structuredClone(p);x.name.he='';assert.ok(publicationErrors(x).some(e=>e.includes('HE')))});
test('owner parity override still requires confirmed pricing',()=>assert.ok(publicationErrors({...p,basePrice:null},true).length));
test('required variant selections checked',()=>assert.ok(publicationErrors({...p,variants:[{...p.variants[0],options:{}}]}).length));
test('order lifecycle blocks skipped quality check',()=>assert.throws(()=>assertTransition('in_production','shipped')));
test('quality check can return to production',()=>assert.doesNotThrow(()=>assertTransition('quality_check','in_production')));
test('terminal cancelled order cannot mutate',()=>assert.deepEqual(transitions('cancelled'),[]));
test('content staff cannot access orders/private settings',()=>{assert.equal(can('content_manager','orders'),false);assert.equal(can('content_manager','settings'),false)});
test('order staff cannot edit prices',()=>assert.equal(can('order_manager','products'),false));
test('customer cannot enter admin',()=>assert.equal(can('customer','dashboard'),false));
test('normalized tracking phones match',()=>assert.equal(normalizeContact('050-123-4567'),'+972501234567'));
test('tracking HMAC stable and contact-specific',async()=>{const s='a'.repeat(32);assert.equal(await contactHash(' OWNER@EXAMPLE.COM ',s),await contactHash('owner@example.com',s));assert.notEqual(await contactHash('a@example.com',s),await contactHash('b@example.com',s))});
test('weak tracking secret rejected',async()=>assert.rejects(contactHash('x','short')));
test('constant time equality detects length/content mismatch',()=>{assert.equal(constantTimeEqual('abc','abc'),true);assert.equal(constantTimeEqual('abc','abcd'),false);assert.equal(constantTimeEqual('abc','abd'),false)});
for(const l of ['ar','he','en'] as const)test(`locale ${l} preserves product URL`,()=>assert.equal(localePath('/en/product/polaris?x=1',l),`/${l}/product/polaris?x=1`));
test('typo tolerant search',()=>assert.equal(searchMatch(p,'Zenit'),true));
test('localized Hebrew search',()=>assert.equal(searchMatch(p,'עגילי'),true));
test('delivery window uses configured days',()=>assert.equal(deliveryRange(10,14,new Date('2026-01-01'))[1].toISOString().slice(0,10),'2026-01-15'));
test('invalid lead range rejected',()=>assert.throws(()=>deliveryRange(14,10)));
test('Arabic customer formatting always uses Western digits',()=>{for(const value of [formatMoney(38000,'ar'),formatNumber(10,'ar'),formatDate('2026-09-18T00:00:00Z','ar')]){assert.match(value,/[0-9]/);assert.doesNotMatch(value,/[٠-٩]/)}});
test('Arabic ships its own weighted typeface and the header avoids a native language select',()=>{const main=readFileSync(new URL('../../src/main.tsx',import.meta.url),'utf8');const layout=readFileSync(new URL('../../src/components/Layout.tsx',import.meta.url),'utf8');assert.match(main,/noto-naskh-arabic\/arabic-600\.css/);assert.match(main,/noto-naskh-arabic\/arabic-700\.css/);assert.match(layout,/language-trigger/);assert.doesNotMatch(layout,/<select\s+className="language/)});
for(const [key,v] of Object.entries(words))test(`translation parity: ${key}`,()=>assert.ok(parity(v)));
test('notification idempotency separates channel and audience',()=>{const n={eventId:'x',channel:'email' as const,audience:'customer' as const};assert.equal(notificationKey(n),notificationKey({...n}));assert.notEqual(notificationKey(n),notificationKey({...n,audience:'owner'}))});
test('media MIME extension spoof rejected',()=>assert.equal(mediaAllowed('image/jpeg',100,'photo.svg'),false));
test('oversize media rejected',()=>assert.equal(mediaAllowed('image/jpeg',21*1024*1024,'photo.jpg'),false));
test('responsive image source allowed',()=>assert.equal(mediaAllowed('image/webp',100,'photo.webp'),true));
test('checkout rejects client total injection',()=>assert.equal(checkoutSchema.safeParse({total:1}).success,false));
test('email markup escaped',()=>assert.equal(escapeHtml('<script>'), '&lt;script&gt;'));
test('public order omits internal data',()=>{const x={id:'x',supplierReference:'SECRET',internalNotes:'SECRET',customer:{email:'private@example.com'}} as AdminOrder;const result=publicOrder(x);assert.equal('supplierReference' in result,false);assert.equal('customer' in result,false)});
